// src/components/warp-view-spectrum/warp-view-spectrum.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Element, Listen, Prop, Watch} from "@stencil/core";
import {ChartLib} from "../../utils/chart-lib";
import {DataModel} from "../../model/dataModel";
import {Param} from "../../model/param";
import {Logger} from "../../utils/logger";
import {GTSLib} from "../../utils/gts.lib";
import moment from "moment";
import { ColorLib } from "../../utils/color-lib";

/**
 *
 */
export class WarpViewSpectrumParam {
  range: string = 'd';
  granularity: string = '10 m';
  scale: number = 24;
  interval: 6
}


@Component({
  tag: 'warp-view-spectrum',
  styleUrl: 'warp-view-spectrum.scss',
  shadow: true
})
export class WarpViewSpectrum {
  @Prop() responsive: boolean = false;
  @Prop() showLegend: boolean = true;
  @Prop() data: DataModel | any[] | string;
  @Prop() options: Param = new Param();
  @Prop({mutable: true}) width = '';
  @Prop({mutable: true}) height = '';

  @Element() el: HTMLElement;

  private uuid = 'spectrum-' + ChartLib.guid().split('-').join('');
  private LOG: Logger = new Logger(WarpViewSpectrum);
  private _options: Param = {
    gridLineColor: '#8e8e8e',
    spectrum: new WarpViewSpectrumParam()
  };
  private resizeTimer;
  private parentWidth = -1;
  private heatMapData: any;

  @Listen('window:resize')
  onResize() {
    if (this.el.parentElement.clientWidth !== this.parentWidth) {
      this.parentWidth = this.el.parentElement.clientWidth;
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.LOG.debug(['onResize'], this.el.parentElement.clientWidth);
        this.drawChart();
      }, 250);
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | any[], oldValue: DataModel | any[]) {
    if (oldValue !== newValue) {
      this.LOG.debug(['data'], newValue);
      this.drawChart();
    }
  }

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if (oldValue !== newValue) {
      this.LOG.debug(['options'], newValue);
      this.drawChart();
    }
  }

  private drawChart() {
    this._options = ChartLib.mergeDeep(this._options, this.options);
    this.height = (this.responsive ? this.el.parentElement.clientHeight : this.height || 600) + '';
    this.width = (this.responsive ? this.el.parentElement.clientWidth : this.width || 800) + '';
    const color = this._options.gridLineColor;
    if (!this.data) return;
    let data: any = this.data;
    if (typeof data === 'string') {
      data = JSON.parse(data as string);
    }

    if (GTSLib.isArray(data) && data[0] && (data[0] instanceof DataModel || data[0].hasOwnProperty('data'))) {
      data = data[0];
    }
    let dataList: any[];
    if (data instanceof DataModel || data.hasOwnProperty('data')) {
      dataList = data.data as any[];
    } else {
      dataList = data;
    }
    this.heatMapData = this.parseData(GTSLib.flatDeep(dataList));
    /*
        if(!this._chart) {
          this._chart = new HeatMap({
            yAxis: { labels: this.formatAxis(dataList), isInversed: true },
            xAxis: {
              increment: 1,
              interval: this._options.spectrum.interval,
              minimum: 0,
              maximum: (this._options.spectrum.scale - 1) * this._options.spectrum.interval,
              labels: WarpViewSpectrum.buildLabels()
            },
            renderingMode: 'Canvas',
            dataSource: dataList,
            paletteSettings: {
              emptyPointColor: 'transparent',
              palette: [
                { color: 'rgb(255,0,255)' },
                { color: 'rgb(0,0,255)' },
                { color: 'rgb(0,255,0)' },
                { color: 'rgb(255,255,0)' },
                { color: 'rgb(255,0,0)' },
              ],
              type: 'Gradient'
            },
            legendSettings: {
              visible: true,
              position: 'Bottom',
              width: '75%',
              enableSmartLegend: true
            },
            showTooltip: false,
            cellSettings: {
              border: {
                width: 0
              },
              showLabel: false,
            },
          });

          this._chart.appendTo(ctx);
        } else {
          this._chart.dataSource =dataList;
        }
    */
  }

  static buildLabels() {
    const r = [];
    for (let i = 0; i < 24 * 6; i++) {
      const j = i / 6;
      if (j - Math.floor(j) === 0) {
        if (j < 10) {
          r.push('0' + j + ':00');
        } else {
          r.push(j + ':00');
        }
      } else {
        r.push('');
      }
    }
    return r;
  }

  formatAxis(labels: string[]) {
    const formatedLabels = [];
    labels.forEach(timestamp => {
      const ts = Math.floor(parseInt(timestamp) / 1000);
      formatedLabels.push(moment.utc(ts).format("D MMM YYYY"));
    });
    return formatedLabels
  }

  private parseData(dataList: any[]) {
    const details = [];
    let values = [];
    const dates = [];
    const data = {};
    const reducer = (accumulator, currentValue) => accumulator + parseInt(currentValue);
    this.LOG.debug(['parseData'], dataList);
    dataList.forEach((gts, i) => {
      const name = GTSLib.serializeGtsMetadata(gts);
      gts.v.forEach(v => {
        const refDate = moment.utc(v[0] / 1000).startOf('day').toISOString();
        if(!data[refDate]) {
          data[refDate] = [];
        }
        if(!values[refDate]) {
          values[refDate] = [];
        }
        dates.push(v[0] / 1000);
        values[refDate].push(v[v.length - 1]);
        data[refDate].push({
          name: name,
          date: v[0] / 1000,
          value: v[v.length - 1],
          color: ColorLib.getColor(i),
          id: i
        });
      });
    });
    Object.keys(data).forEach((d:string) => {
      details.push({
        date: moment.utc(d),
        total: values[d].reduce(reducer),
        details: data[d],
        summary: []
      })
    });
    return details;
  }

  componentDidLoad() {
    this.drawChart()
  }

  render() {
    return <div class="wrapper">
      <calendar-heatmap data={this.heatMapData} overview={'global'}></calendar-heatmap>
    </div>;
  }

}

// projects/warpview-ng/src/lib/elements/warp-view-spectrum/warp-view-spectrum.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, ElementRef, Input, ViewEncapsulation} from '@angular/core';
import {VisibilityState, WarpViewComponent} from '../warp-view-component';
import {DataModel} from '../../model/dataModel';
import {Param} from '../../model/param';
import {ColorLib} from '../../utils/color-lib';
import {GTSLib} from '../../utils/gts.lib';
import {GTS} from '../../model/GTS';
import moment from 'moment-timezone';
import {SizeService} from '../../services/resize.service';
import {Logger} from '../../utils/logger';

@Component({
  selector: 'warpview-spectrum',
  templateUrl: './warp-view-spectrum.component.html',
  styleUrls: ['./warp-view-spectrum.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewSpectrumComponent extends WarpViewComponent {

  @Input('type') set type(type: string) {
    this._type = type;
    this.drawChart();
  }

  layout: Partial<any> = {
    showlegend: false,
    xaxis: {},
    yaxis: {},
  };
  private _type = 'histogram2d';
  private visibility: boolean[] = [];
  private visibilityStatus: VisibilityState = 'unknown';
  private maxTick = 0;
  private minTick = 0;
  private visibleGtsId = [];

  constructor(
    public el: ElementRef,
    public sizeService: SizeService,
  ) {
    super(el, sizeService);
    this.LOG = new Logger(WarpViewSpectrumComponent, this._debug);
  }

  update(options: Param): void {
    this.drawChart();
  }

  private drawChart() {
    if (!this.initChart(this.el)) {
      return;
    }
    this.plotlyConfig.scrollZoom = true;
    this.buildGraph();
  }

  protected convert(data: DataModel): Partial<any>[] {
    const type = this._options.histo || {histnorm: 'density', histfunc: 'count'};
    const dataset: Partial<any>[] = [];
    this.LOG.debug(['convert'], this._options);
    this.visibility = [];
    let gtsList = GTSLib.flatDeep(GTSLib.flattenGtsIdArray(data.data as any[], 0).res);
    this.maxTick = Number.NEGATIVE_INFINITY;
    this.minTick = Number.POSITIVE_INFINITY;
    this.visibleGtsId = [];
    const nonPlottable = gtsList.filter(g => {
      this.LOG.debug(['convert'], GTSLib.isGtsToPlot(g));
      return (g.v && !GTSLib.isGtsToPlot(g));
    });
    gtsList = gtsList.filter(g => {
      return (g.v && GTSLib.isGtsToPlot(g));
    });
    // initialize visibility status
    if (this.visibilityStatus === 'unknown') {
      this.visibilityStatus = gtsList.length > 0 ? 'plottableShown' : 'nothingPlottable';
    }

    if (this._options.timeMode && this._options.timeMode === 'timestamp') {
      this.layout.xaxis.type = 'linear';
    } else {
      this.layout.xaxis.type = 'date';
    }
    gtsList.forEach((gts: GTS) => {
      if (gts.v && GTSLib.isGtsToPlot(gts)) {
        const label = GTSLib.serializeGtsMetadata(gts);
        const color = ColorLib.getColor(gts.id, this._options.scheme);
        const series: Partial<any> = {
          type: this._type,
          histnorm: type.histnorm || 'density',
          histfunc: type.histfunc || 'count',
          contours: {
            showlabels: true,
            labelfont: {
              color: 'white'
            }
          },
          colorbar: {
            tickcolor: this.getGridColor(this.el.nativeElement),
            thickness: 0,
            tickfont: {
              color: this.getLabelColor(this.el.nativeElement)
            },
            x: 1 + gts.id / 20,
            xpad: 0
          },
          showscale: this.showLegend,
          colorscale: ColorLib.getColorGradient(gts.id, this._options.scheme),
          autocolorscale: false,
          name: label,
          text: label,
          x: [],
          y: [],
          line: {color},
          hoverinfo: 'none',
          connectgaps: false,
          visible: this._hiddenData.filter(h => h === gts.id).length >= 0,
        };
        gts.v.forEach(value => {
          const ts = value[0];
          (series.y as any[]).push(value[value.length - 1]);
          if (this._options.timeMode && this._options.timeMode === 'timestamp') {
            (series.x as any).push(ts);
          } else {
            (series.x as any).push(moment(Math.floor(ts / this.divider)).utc(true).toDate());
          }
        });
        dataset.push(series);
      }
    });
    this.LOG.debug(['convert', 'dataset'], dataset);

    return dataset;
  }

  private buildGraph() {
    this.LOG.debug(['drawChart', 'this.layout'], this.responsive);
    this.LOG.debug(['drawChart', 'this.layout'], this.layout);
    this.LOG.debug(['drawChart', 'this.plotlyConfig'], this.plotlyConfig);
    this.layout.showlegend = this.showLegend;
    this.layout.yaxis.color = this.getGridColor(this.el.nativeElement);
    this.layout.xaxis.color = this.getGridColor(this.el.nativeElement);
    this.loading = false;
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div id="chartContainer"  #chartContainer>
  <warpview-spinner *ngIf="loading" message="Parsing data"></warpview-spinner>
  <div *ngIf="!loading">
    <warpview-plotly #graph
                 [data]="plotlyData" [layout]="layout" [config]="plotlyConfig" (afterPlot)="afterPlot()"
                 (relayout)="relayout($event)" (hover)="hover($event)" (unhover)="unhover()"
                 [updateOnLayoutChange]="true" [updateOnDataChange]="true" [debug]="debug"
                 [style]="{position: 'relative', width: '100%', height: '100%'}"></warpview-plotly>
  </div>
  <div #toolTip class="tooltip"></div>
</div>
