// projects/warpview-ng/src/lib/elements/warp-view-image/warp-view-image.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {AfterViewInit, Component, ElementRef, HostListener, Input, ViewEncapsulation} from '@angular/core';
import {WarpViewComponent} from '../warp-view-component';
import {Param} from '../../model/param';
import {ChartLib} from '../../utils/chart-lib';
import {DataModel} from '../../model/dataModel';
import {GTSLib} from '../../utils/gts.lib';
import {SizeService} from '../../services/resize.service';
import {Logger} from '../../utils/logger';

/**
 *
 */
@Component({
  selector: 'warpview-image',
  templateUrl: './warp-view-image.component.html',
  styleUrls: ['./warp-view-image.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewImageComponent extends WarpViewComponent implements AfterViewInit {
  @Input('imageTitle') imageTitle = '';

  toDisplay: string[];

  private resizeTimer;
  private parentWidth = -1;

  constructor(
    public el: ElementRef,
    public sizeService: SizeService,
  ) {
    super(el, sizeService);
    this.LOG = new Logger(WarpViewImageComponent, this._debug);
  }

  ngAfterViewInit(): void {
    this.LOG.debug(['ngAfterViewInit'], this._options);
    this.drawChart();
  }

  update(options: Param, refresh: boolean): void {
    this.drawChart();
  }

  @HostListener('window:resize')
  onResize() {
    if (this.el.nativeElement.parentElement.clientWidth !== this.parentWidth || this.parentWidth <= 0) {
      this.parentWidth = this.el.nativeElement.parentElement.clientWidth;
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        if (this.el.nativeElement.parentElement.clientWidth > 0) {
          this.LOG.debug(['onResize'], this.el.nativeElement.parentElement.clientWidth);
          this.drawChart();
        } else {
          this.onResize();
        }
      }, 150);
    }
  }

  private drawChart() {
    if (!this._data || !this._data.data || this._data.data.length === 0) {
      return;
    }
    this.initChart(this.el);
    this.toDisplay = [];
    let gts: DataModel = this._data;
    this.LOG.debug(['drawChart', 'gts'], gts);
    if (typeof gts === 'string') {
      try {
        gts = JSON.parse(gts as string);
      } catch (error) {
        // empty : it's a base64 string
      }
    }
    if (gts.data && gts.data.length > 0 && GTSLib.isEmbeddedImage(gts.data[0])) {
      this._options = ChartLib.mergeDeep(this._options, gts.globalParams || {}) as Param;
      this.toDisplay.push(gts.data[0]);
    } else if (gts.data && GTSLib.isEmbeddedImage(gts.data)) {
      this.toDisplay.push(gts.data as string);
    }
    this.LOG.debug(['drawChart', 'this.data', 'this.toDisplay'], this.data, this.toDisplay);
  }

  getStyle() {
    this.LOG.debug(['getStyle'], this._options);
    if (!this._options) {
      return {};
    } else {
      const style: any = {'background-color': this._options.bgColor || 'transparent', width: this.width, height: 'auto'};
      if (this._options.fontColor) {
        style.color = this._options.fontColor;
      }
      this.LOG.debug(['getStyle', 'style'], style);
      return style;
    }
  }

  protected convert(data: DataModel): any[] {
    return [];
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div>
  <p class="noData" *ngIf="noDAta">No data to display</p>
  <div class="chart-container" id="wrapper" *ngIf="toDisplay">
    <div *ngFor="let img of toDisplay" [ngStyle]="getStyle()">
      <img [src]="img" class="responsive" alt="Result"/>
    </div>
  </div>
  <warpview-spinner *ngIf="!toDisplay" message="Parsing data"></warpview-spinner>
</div>

// src/components/warp-view-image/warp-view-image.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import { Component, Element, Listen, Prop, Watch } from "@stencil/core";
import { Logger } from "../../utils/logger";
import { Param } from "../../model/param";
import { GTSLib } from "../../utils/gts.lib";
import { DataModel } from "../../model/dataModel";
import { ChartLib } from "../../utils/chart-lib";

/**
 * Display component
 */
@Component({
  tag: 'warp-view-image',
  styleUrl: 'warp-view-image.scss',
  shadow: true
})
export class WarpViewImage {
  @Prop() imageTitle: string = '';
  @Prop() responsive: boolean = false;
  @Prop() data: DataModel | any[] | string;
  @Prop() options: Param = new Param();
  @Prop({ mutable: true }) width = '';
  @Prop({ mutable: true }) height = '';

  @Element() el: HTMLElement;

  private LOG: Logger = new Logger(WarpViewImage);
  private _options: Param = new Param();
  private toDisplay: string[];
  private resizeTimer;

  @Listen('window:resize')
  onResize() {
    clearTimeout(this.resizeTimer);
    this.resizeTimer = setTimeout(() => {
      this.LOG.debug([ 'onResize' ], this.el.parentElement.clientWidth);
      this.drawChart();
    }, 250);
  }

  @Watch('data')
  private onData(newValue: DataModel | any[] | string | number, oldValue: DataModel | any[] | string | number) {
    if(oldValue !== newValue) {
      this.LOG.debug([ 'onData' ], newValue);
      this.drawChart();
    }
  }

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if(oldValue !== newValue) {
      this.LOG.debug([ 'options' ], newValue);
      this.drawChart();
    }
  }

  private drawChart() {
    this.LOG.debug([ 'drawChart' ], [ this.options, this._options ]);
    this._options = ChartLib.mergeDeep(this._options, this.options);
    this.height = (this.responsive ? this.el.parentElement.clientHeight : this.height || 600) + 'px';
    this.width = (this.responsive ? this.el.parentElement.clientWidth : this.width || 800) + 'px';
    this.toDisplay = [];
    if(!this.data) return;
    let gts: any = this.data;
    if(typeof gts === 'string') {
      try {
        gts = JSON.parse(gts as string);
      } catch(error) {
        // empty : it's a base64 string
      }
    }
    if(gts instanceof DataModel || gts.hasOwnProperty('data')) {
      if(gts.data && gts.data.length > 0 && GTSLib.isEmbeddedImage(gts.data[ 0 ])) {
        this._options = ChartLib.mergeDeep(this._options, gts.globalParams || {});
        this.toDisplay.push(gts.data[ 0 ]);
      } else if(gts.data && GTSLib.isEmbeddedImage(gts.data)) {
        this.toDisplay.push(gts.data as string);
      }
    } else {
      if(GTSLib.isArray(gts)) {
        (gts as string[]).forEach(d => {
          if(GTSLib.isEmbeddedImage(d)) {
            this.toDisplay.push(d)
          }
        })
      }
    }
    this.LOG.debug([ 'drawChart' ], [ this.data, this.toDisplay ]);
  }

  private getStyle() {
    this.LOG.debug([ 'getStyle' ], this._options);
    if(!this._options) {
      return {};
    } else {
      const style: any = { 'background-color': this._options.bgColor || 'transparent' };
      if(this._options.fontColor) {
        style.color = this._options.fontColor;
      }
      this.LOG.debug([ 'getStyle', 'style' ], style);
      return style;
    }
  }

  componentDidLoad() {
    this.LOG.debug([ 'componentDidLoad' ], this._options);
    this.drawChart()
  }

  render() {
    return <div>
      {this.toDisplay ?
        <div class="chart-container" id="#wrapper">
          {this.toDisplay.map((img) =>
            <div style={this.getStyle()}>
              <img src={img} class="responsive" alt="Result"/>
            </div>
          )}
        </div>
        :
        <warp-view-spinner/>
      }
    </div>;
  }
}
