// src/app/elements/warp-view-annotation/warp-view-annotation.component.ts
/*
 * Copyright 2019 SenX S.A.S.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
  ViewEncapsulation
} from '@angular/core';
import {WarpViewComponent} from '../warp-view-component';
import {Param} from '../../model/param';
import {Logger} from '../../utils/logger';
import {ChartLib} from '../../utils/chart-lib';
import * as moment from 'moment-timezone';
import {DataModel} from '../../model/dataModel';
import {GTSLib} from '../../utils/gts.lib';
import {GTS} from '../../model/GTS';
import {ColorLib} from '../../utils/color-lib';
import {SizeService} from '../../services/resize.service';

@Component({
  selector: 'warpview-annotation',
  templateUrl: './warp-view-annotation.component.html',
  styleUrls: ['./warp-view-annotation.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewAnnotationComponent extends WarpViewComponent implements OnInit, OnDestroy {
  @ViewChild('toolTip') toolTip: ElementRef;
  @ViewChild('graph') graph: ElementRef;
  @ViewChild('date') date: ElementRef;

  @Input() set hiddenData(hiddenData: number[]) {
    if (this._chart && hiddenData) {
      this.LOG.debug(['hiddenData'], hiddenData);
      this._hiddenData = hiddenData;
      if (this._chart) {
        this.drawChart();
      }
    }
  }

  @Input() set type(type: string) {
    this._type = type;
    this.drawChart();
  }

  @Input() standalone = true;
  @Output() pointHover = new EventEmitter<any>();
  @Output() warpViewChartResize = new EventEmitter<any>();
  @Output() chartDraw = new EventEmitter<any>();

  displayExpander = true;

  private _type = 'line';
  private visibility: boolean[] = [];
  private expanded = false;
  private trimmed;
  private maxTick: number;
  private minTick: number;
  private visibleGtsId = [];
  private dataHashset = {};

  protected layout: Partial<any> = {
    showlegend: false,
    hovermode: 'closest',
    xaxis: {},
    autosize: false,
    yaxis: {
      showticklabels: true,
      fixedrange: true,
      dtick: 1,
      tick0: 0,
      automargin: false,
      showline: false,
      tickfont: {
        color: 'transparent'
      }
    },
    margin: {
      t: 20,
      b: 0,
      r: 0,
      l: 50
    },
  };

  constructor(private el: ElementRef, private sizeService: SizeService) {
    super();
    this.LOG = new Logger(WarpViewAnnotationComponent, this._debug);
    this.sizeService.sizeChanged$.subscribe(() => {
      if (this._chart) {
        this.layout.width = (this.el.nativeElement as HTMLElement).parentElement.getBoundingClientRect().width;
        this.height = (this.expanded ? 40 * this.plotlyData.length : 40) + this.layout.margin.t;
        this.layout.height = this.height;
        Plotly.relayout(this.graph.nativeElement, {
          height: this.layout.height,
          width: this.layout.width
        });
      }
    });
  }

  ngOnInit() {
  }

  ngOnDestroy(): void {
    if (this._chart) {
      this._chart.removeAllListeners('plotly_hover');
      this._chart.removeAllListeners('plotly_unhover');
      this._chart.removeAllListeners('plotly_relayout');
      Plotly.purge(this._chart);
    }
  }

  @HostListener('keydown', ['$event'])
  @HostListener('document:keydown', ['$event'])
  handleKeyDown($event: KeyboardEvent) {
    if ($event.key === 'Control') {
      this.trimmed = setInterval(() => {
        if (!!this.toolTip.nativeElement.querySelector('#tooltip-body')) {
          this.toolTip.nativeElement.querySelector('#tooltip-body').classList.add('full');
        }
      }, 100);
    }
  }

  @HostListener('keyup', ['$event'])
  @HostListener('document:keyup', ['$event'])
  handleKeyup($event: KeyboardEvent) {
    this.LOG.debug(['document:keyup'], $event);
    if ($event.key === 'Control') {
      if (!!this.toolTip.nativeElement.querySelector('#tooltip-body')) {
        if (this.trimmed) {
          clearInterval(this.trimmed);
        }
        this.toolTip.nativeElement.querySelector('#tooltip-body').classList.remove('full');
      }
    }
  }

  update(options: Param, refresh: boolean): void {
    this._options = ChartLib.mergeDeep(this._options, options) as Param;
    this.drawChart();
  }

  updateBounds(min, max) {
    this.LOG.debug(['updateBounds'], min, max, this._options);
    this._options.bounds.minDate = min;
    this._options.bounds.maxDate = max;
    if (!!this._chart) {
      if (this._options.timeMode && this._options.timeMode === 'timestamp') {
        this.layout.xaxis.range = [min, max];
      } else {
        this.layout.xaxis.range = [
          moment.tz(min, this._options.timeZone).toISOString(true),
          moment.tz(max, this._options.timeZone).toISOString(true)
        ];
      }
      Plotly.relayout(this.graph.nativeElement, {
        'xaxis.range': this.layout.xaxis.range
      });
    }
  }

  drawChart(reparseNewData: boolean = false) {
    if (!this.initiChart(this.el)) {
      return;
    }
    this.LOG.debug(['drawChart', 'this.plotlyData'], this.plotlyData);
    this.LOG.debug(['drawChart', 'hiddenData'], this._hiddenData);
    this.LOG.debug(['drawChart', 'this._options.bounds'], this._options.bounds);
    this.layout.yaxis.color = this.getGridColor(this.el.nativeElement);
    this.layout.xaxis.color = this.getGridColor(this.el.nativeElement);
    this.displayExpander = (this.plotlyData.length > 1);
    const calculatedHeight = (this.expanded ? 40 * this.plotlyData.length : 40) + this.layout.margin.t;
    this.height = calculatedHeight;
    this.LOG.debug(['drawChart', 'height'], this.height, this.plotlyData.length, calculatedHeight);
    this.layout.yaxis.range = [0, this.expanded ? this.plotlyData.length : 1];
    this.layout.height = this.height;
    this.LOG.debug(['drawChart', 'this.layout'], this.responsive, reparseNewData);
    this.LOG.debug(['drawChart', 'this.layout'], this.layout);
    this.LOG.debug(['drawChart', 'this.plotlyConfig'], this.plotlyConfig);
    if (this.standalone) {
      this.plotlyConfig.scrollZoom = true;
    }
    Plotly.newPlot(this.graph.nativeElement, this.plotlyData, this.layout, this.plotlyConfig).then(plot => {
      this.loading = false;
      this._chart = plot;
      this.chartDraw.emit();
      this._chart.on('plotly_hover', (data: any) => {
        this.LOG.debug(['plotly_hover'], data);
        const tooltip = this.toolTip.nativeElement;
        this.pointHover.emit({
          x: data.event.offsetX,
          y: data.event.offsetY
        });
        const layout = this.graph.nativeElement.getBoundingClientRect();
        tooltip.style.opacity = '1';
        tooltip.style.display = 'block';
        const lineHeight = (this.height - this.layout.margin.t) / (this.expanded ? this.plotlyData.length : 1);
        tooltip.style.top =
          ((this.expanded ? this.plotlyData.length - Math.floor(data.points[0].y + 0.5) + 1 : 1) *
            lineHeight - lineHeight / 2 - 10 + this.layout.margin.t) + 'px';
        tooltip.classList.remove('right', 'left');
        this.LOG.debug(['tooltip'], data);
        this.date.nativeElement.innerHTML = this._options.timeMode === 'timestamp'
          ? data.xvals[0]
          : (moment(data.xvals[0]).utc().toISOString() || '')
            .replace('Z', this._options.timeZone === 'UTC' ? 'Z' : '');
        tooltip.innerHTML = `<div class="tooltip-body trimmed" id="tooltip-body">
        <span>${GTSLib.formatLabel(data.points[0].data.name)}: </span>
        <span class="value">${data.yvals[0]}</span>
      </div>`;
        if (data.event.offsetX > layout.width / 2) {
          tooltip.classList.add('left');
        } else {
          tooltip.classList.add('right');
        }
        tooltip.style.pointerEvents = 'none';
        return;
      });
      this._chart.on('plotly_unhover', () => {
        this.toolTip.nativeElement.style.display = 'none';
      });
    });
  }

  protected convert(data: DataModel): Partial<any>[] {
    const dataset: Partial<any>[] = [];
    const divider = GTSLib.getDivider(this._options.timeUnit);
    this.visibility = [];
    let gtsList = GTSLib.flatDeep(GTSLib.flattenGtsIdArray(data.data as any[], 0).res);
    this.maxTick = Number.NEGATIVE_INFINITY;
    this.minTick = Number.POSITIVE_INFINITY;
    this.visibleGtsId = [];
    const nonPlottable = gtsList.filter(g => {
      return (g.v && GTSLib.isGtsToPlot(g));
    });
    gtsList = gtsList.filter(g => {
      return (g.v && !GTSLib.isGtsToPlot(g));
    });
    gtsList.forEach((gts: GTS, i) => {
      if (gts.v) {
        const label = GTSLib.serializeGtsMetadata(gts);
        const color = ColorLib.getColor(gts.id, this._options.scheme);
        const series: Partial<any> = {
          type: 'scatter',
          mode: 'markers',
          name: label,
          text: label,
          x: [],
          y: [],
          line: {},
          hoverinfo: 'none',
          connectgaps: false,
          visible: this._hiddenData.filter(h => h === gts.id).length >= 0,
          'line.color': color,
          marker: {
            symbol: 'line-ns-open',
            color,
            size: 20,
            width: 5,
          }
        };
        this.visibility.push(true);
        this.visibleGtsId.push(gts.id);
        if (this._options.timeMode && this._options.timeMode === 'timestamp') {
          this.layout.xaxis.type = 'linear';
        } else {
          this.layout.xaxis.type = 'date';
        }
        gts.v.forEach(value => {
          const ts = value[0];
          if (ts < this.minTick) {
            this.minTick = ts;
          }
          if (ts > this.maxTick) {
            this.maxTick = ts;
          }
          (series.y as any[]).push((this.expanded ? i : 0) + 0.5);
          if (this._options.timeMode && this._options.timeMode === 'timestamp') {
            (series.x as any[]).push(ts);
          } else {
            const timestamp = Math.floor(ts / divider);
            (series.x as any[]).push(moment(timestamp).utc(true).toDate());
          }
        });
        dataset.push(series);
      }
    });
    if (nonPlottable.length > 0) {
      nonPlottable.forEach(g => {
        g.v.forEach(value => {
          const ts = value[0];
          if (ts < this.minTick) {
            this.minTick = ts;
          }
          if (ts > this.maxTick) {
            this.maxTick = ts;
          }
        });
      });
      // if there is not any plottable data, we must add a fake one with id -1. This one will always be hidden.
      if (0 === gtsList.length) {
        if (!this.dataHashset[this.minTick]) {
          this.dataHashset[this.minTick] = [0];
        }
        if (!this.dataHashset[this.maxTick]) {
          this.dataHashset[this.maxTick] = [0];
        }
        this.visibility.push(false);
        this.visibleGtsId.push(-1);
      }
    }

    return dataset;
  }

  private toggle() {
    this.expanded = !this.expanded;
    this.drawChart();
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div id="chartContainer" #chartContainer>
  <div class="date" #date></div>
  <button *ngIf="displayExpander && plotlyData && plotlyData.length > 1" class="expander" (click)="toggle()"
          title="collapse/expand">+/-
  </button>
  <div #toolTip class="tooltip"></div>
  <warpview-spinner *ngIf="loading" message="Parsing data"></warpview-spinner>
  <div *ngIf="!loading">
    <div class="upperLine" [ngStyle]="{left: standalone? '50px': '0px'}"></div>
    <plotly-plot #graph
                 [data]="plotlyData" [layout]="layout" [config]="plotlyConfig" (afterPlot)="afterPlot()"
                 className="chart" (hover)="hover($event)" (unhover)="unhover()"
                 [updateOnLayoutChange]="true" [updateOnDataChange]="true" [debug]="debug"
                 [style]="{position: 'relative', width: '100%', height: '100%'}"></plotly-plot>
  </div>
</div>

// src/components/warp-view-annotation/warp-view-annotation.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import Chart from 'chart.js';
import {Component, Element, Event, EventEmitter, Listen, Prop, State, Watch} from '@stencil/core';
import {GTSLib} from '../../utils/gts.lib';
import {ColorLib} from "../../utils/color-lib";
import {Logger} from "../../utils/logger";
import {Param} from "../../model/param";
import {ChartLib} from "../../utils/chart-lib";
import {DataModel} from "../../model/dataModel";
import {GTS} from "../../model/GTS";
import moment from "moment-timezone";

/**
 * @prop --warp-view-chart-width: Fixed width if not responsive
 * @prop --warp-view-chart-height: Fixed height if not responsive
 */
@Component({
  tag: "warp-view-annotation",
  styleUrl: "warp-view-annotation.scss",
  shadow: true
})
export class WarpViewAnnotation {
  @Prop() responsive: boolean = false;
  @Prop() showLegend: boolean = true;
  @Prop() data: DataModel | DataModel[] | GTS[] | string;
  @Prop() options: Param = new Param();
  @Prop() hiddenData: number[] = [];
  @Prop() timeMin: number;
  @Prop() timeMax: number;
  @Prop({mutable: true}) width = '';
  @Prop({mutable: true}) height = '';
  @Prop() standalone = true;
  @Prop() debug = false;

  @State() displayExpander = true;

  @Event() pointHover: EventEmitter;

  @Element() el: HTMLElement;

  private _chart: Chart;
  private _mapIndex = {};
  private LOG: Logger;
  private _options: Param = {
    gridLineColor: '#000000',
    timeMode: 'date'
  };
  private canvas: HTMLCanvasElement;
  private tooltip: HTMLDivElement;
  private date: HTMLDivElement;
  private resizeTimer;
  private parentWidth = -1;
  private _height = '0';
  private expanded = false;

  @Listen('window:resize')
  onResize() {
    if (this.el.parentElement.clientWidth !== this.parentWidth) {
      this.parentWidth = this.el.parentElement.clientWidth;
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.LOG.debug(['onResize'], this.el.parentElement.clientWidth);
        this.drawChart();
      }, 250);
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | GTS[], oldValue: DataModel | GTS[]) {
    if (oldValue !== newValue) {
      this.LOG.debug(['data'], newValue);
      this.drawChart();
    }
  }

  @Watch("options")
  onOptions(newValue: Param, oldValue: Param) {
    if (JSON.stringify(oldValue) !== JSON.stringify(newValue)) {
      this.LOG.debug(['options'], [newValue, this.hiddenData]);
      if (this._chart) {
        this.drawChart();
      }
    }
  }

  @Watch("hiddenData")
  hideData(newValue, oldValue) {
    if (oldValue !== newValue && this._chart) {
      this.LOG.debug(['hiddenData'], newValue);
      const hiddenData = newValue;
      if (this._chart) {
        Object.keys(this._mapIndex).forEach(key => {
          const hidden = hiddenData.indexOf(parseInt(key)) >= 0;
          this.LOG.debug(['hiddenDataHidden'], [key, hidden, this._chart.getDatasetMeta(this._mapIndex[key])]);
        });
        this.drawChart();
        setTimeout(() => {
          this._chart.update();
        }, 250);
      }
    }
  }

  @Watch("timeMin")
  minBoundChange(newValue: number, oldValue: number) {
    if (this._chart) {
      this._chart.options.animation.duration = 0;
      if (oldValue !== newValue && this._chart.options.scales.xAxes[0].time) {
        if (this._options.timeMode === 'timestamp') {
          this._chart.options.scales.xAxes[0].ticks.min = newValue;
        } else {
          if (newValue == 0 && !this.standalone) {
            newValue = 1;
          } //clunky hack for issue #22
          this._chart.options.scales.xAxes[0].time.min = newValue;
        }
        this.LOG.debug(['minBoundChange'], this._chart.options.scales.xAxes[0].time.min);
        this._chart.update();
      }
    }
  }

  @Watch("timeMax")
  maxBoundChange(newValue: number, oldValue: number) {
    if (this._chart) {
      this._chart.options.animation.duration = 0;
      if (oldValue !== newValue && this._chart.options.scales.xAxes[0].time) {
        if (this._options.timeMode === 'timestamp') {
          this._chart.options.scales.xAxes[0].ticks.max = newValue;
        } else {
          if (newValue == 0 && !this.standalone) {
            newValue = 1;
          } //clunky hack for issue #22
          this._chart.options.scales.xAxes[0].time.max = newValue;
        }
        this.LOG.debug(['maxBoundChange'], this._chart.options.scales.xAxes[0].time.max);
        this._chart.update();
      }
    }
  }

  /**
   *
   */
  private drawChart() {
    if (!this.data) {
      return;
    }
    moment.tz.setDefault("UTC");    //force X axis display in UTC
    this._options.timeMode = 'date';
    this._options = ChartLib.mergeDeep(this._options, this.options);
    this.LOG.debug(['drawChart', 'hiddenData'], this.hiddenData);
    let gts = this.parseData(this.data);

    if (!gts || gts.length === 0) {
      return;
    }

    let calculatedHeight = (this.expanded ? 30 * gts.length : 30);
    let height = this.height
    || this.height !== ''
      ? Math.max(calculatedHeight, parseInt(this.height))
      : calculatedHeight;
    this._height = height.toString();
    this.LOG.debug(['drawChart', 'height'], height, gts.length, calculatedHeight);
    this.canvas.parentElement.style.height = height + 'px';
    this.canvas.parentElement.style.width = '100%';
    const color = this._options.gridLineColor;
    const me = this;
    const chartOption = {
      layout: {
        padding: {
          right: 26 //fine tuning, depends on chart element
        }
      },
      legend: {display: this.showLegend},
      responsive: this.responsive,
      animation: {
        duration: 0
      },
      tooltips: {
        enabled: false,
        custom: function (tooltipModel) {
          const layout = me.canvas.getBoundingClientRect();
          if (tooltipModel.opacity === 0) {
            me.tooltip.style.opacity = '0';
            me.date.innerHTML = '';
            return;
          }
          if (tooltipModel.dataPoints && tooltipModel.dataPoints[0]) {
            me.pointHover.emit({
              x: tooltipModel.dataPoints[0].x,
              y: this._eventPosition.y
            });
          } else {
            me.pointHover.emit({x: -100, y: this._eventPosition.y});
          }
          me.tooltip.style.opacity = '1';
          me.tooltip.style.top = (tooltipModel.caretY - 14 + 20) + 'px';
          me.tooltip.classList.remove('right', 'left');
          if (tooltipModel.body) {
            me.LOG.debug(['tooltip'], tooltipModel.title[0]);
            me.date.innerHTML = me._options.timeMode === 'timestamp'
              ? tooltipModel.title[0]
              : moment(tooltipModel.title[0]).utc().toISOString() || '';
            me.tooltip.innerHTML = `<div class="tooltip-body">
  <span>${GTSLib.formatLabel(tooltipModel.body[0].lines[0].gts)}: </span>
  <span class="value">${tooltipModel.body[0].lines[0].value}</span>
</div>`;
          }
          if (tooltipModel.caretX > layout.width / 2) {
            me.tooltip.classList.add('left');
          } else {
            me.tooltip.classList.add('right');
          }
          me.tooltip.style.pointerEvents = 'none';
          return;
        },
        callbacks: {
          title: (tooltipItems, data) => {
            return data.datasets[tooltipItems[0].datasetIndex].data[tooltipItems[0].index].x;
          },
          label: (tooltipItem, data) => {
            return {
              gts: data.datasets[tooltipItem.datasetIndex].label,
              value: data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index].val
            }
          }
        }
      },
      scales: {
        xAxes: [
          {
            display: this.standalone,
            drawTicks: false,
            type: "linear",
            time: {},
            gridLines: {
              zeroLineColor: color,
              color: color,
              display: false
            },
            ticks: {}
          }
        ],
        yAxes: [
          {
            display: true,
            drawTicks: false,
            scaleLabel: {
              display: false
            },
            afterFit: (scaleInstance) => {
              scaleInstance.width = 100; // sets the width to 100px
            },
            gridLines: {
              color: color,
              zeroLineColor: color,
              drawBorder: false
            },
            ticks: {
              display: false,
              min: -0.05,
              max: 1,
              beginAtZero: false,
              stepSize: 1,
              offsetGridLines: true
            }
          }
        ]
      }
    };
    this.LOG.debug(['options'], this._options);
    if (this.expanded) {
      chartOption.scales.yAxes[0].ticks.max = gts.length;
    }

    if (this._options.timeMode === 'timestamp') {
      chartOption.scales.xAxes[0].time = {};
      chartOption.scales.xAxes[0].type = 'linear';
      chartOption.scales.xAxes[0].ticks = {
        fontColor: color,
        min: this.timeMin,
        max: this.timeMax,
        maxRotation: 0,
        minRotation: 0
      };
    } else {
      let tmin: number = (this.timeMin == 0 && !this.standalone) ? 1 : this.timeMin; //clunky hack for issue #22
      let tmax: number = (this.timeMax == 0 && !this.standalone) ? 1 : this.timeMax; //clunky hack for issue #22. introduce a 1millisecond error.
      chartOption.scales.xAxes[0].time = {
        min: tmin,
        max: tmax,
        displayFormats: {
          millisecond: 'HH:mm:ss.SSS',
          second: 'HH:mm:ss',
          minute: 'HH:mm',
          hour: 'HH',
          maxRotation: 0,
          minRotation: 0
        }
      };
      chartOption.scales.xAxes[0].ticks = {
        fontColor: color
      };
      chartOption.scales.xAxes[0].type = 'time';
    }
    this.LOG.debug(['drawChart', 'about to render'], [chartOption, gts]);
    if (this._chart) {
      this._chart.destroy();
    }
    this._chart = new Chart.Scatter(this.canvas, {data: {datasets: gts}, options: chartOption});
    this.onResize();
    this._chart.update();
    // not needed if managed in dataset. will be needed later when optimizing the parseData calls.
    // Object.keys(this._mapIndex).forEach(key => {
    //   this.LOG.debug(['drawChart', 'hide'], [key]);
    //   this._chart.getDatasetMeta(this._mapIndex[key]).hidden = !!this.hiddenData.find(item => item + '' === key);
    // });
  }

  /**
   *
   * @param gts
   * @returns {any[]}
   */
  private parseData(gts) {
    this.LOG.debug(['parseData'], gts);
    let dataList = GTSLib.getData(gts).data;
    this._mapIndex = {};
    if (!dataList || dataList.length === 0) {
      return [];
    } else {
      let dataSet = [];
      dataList = GTSLib.flattenGtsIdArray(dataList as any[], 0).res;
      dataList = GTSLib.flatDeep(dataList) as any[];
      this.LOG.debug(['parseData', 'dataList'], dataList);
      let i = 0;
      dataList = dataList.filter(g => {
        return (g.v && GTSLib.isGtsToAnnotate(g));
      });
      dataList.forEach(g => {
        this.LOG.debug(['parseData', 'will draw'], g);
        let data = [];
        let color = ColorLib.getColor(g.id);
        const myImage = ChartLib.buildImage(1, 30, color);
        g.v.forEach(d => {
          let time = d[0];
          if (this._options.timeMode !== 'timestamp') {
            time = moment(time / GTSLib.getDivider(this._options.timeUnit)).utc(true).valueOf();
          }
          data.push({x: time, y: (this.expanded ? dataList.length - 1 - i : 0) + 0.5, val: d[d.length - 1]});
        });
        let label = GTSLib.serializeGtsMetadata(g);
        this._mapIndex[g.id + ''] = i;
        dataSet.push({
          label: label,
          data: data,
          pointRadius: 5,
          pointHoverRadius: 5,
          pointHitRadius: 5,
          pointStyle: myImage,
          borderColor: color,
          backgroundColor: ColorLib.transparentize(color),
          hidden: this.hiddenData.indexOf(g.id) >= 0
        });
        i++;
      });
      return dataSet;
    }
  }

  componentWillLoad() {
    this.LOG = new Logger(WarpViewAnnotation, this.debug);
  }

  componentDidLoad() {
    this.drawChart();
  }

  render() {
    return <div>
      <div class="date" ref={el => this.date = el}/>
      {this.displayExpander
        ? <button class={'expander'} onClick={() => this.toggle()} title="collapse/expand">+/-</button>
        : ''
      }
      <div
        class="chart-container"
        style={{
          position: "relative",
          width: this.width,
          height: this._height
        }}
      >
        <canvas ref={el => this.canvas = el} width={this.width} height={this._height}/>
      </div>
      <div class="tooltip" ref={el => this.tooltip = el}/>
    </div>;
  }

  private toggle() {
    this.expanded = !this.expanded;
    this.drawChart();
  }
}
