// projects/warpview-ng/src/lib/elements/warp-view-map/warp-view-map.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnInit,
  Output,
  Renderer2,
  ViewChild,
  ViewEncapsulation
} from '@angular/core';
import {Param} from '../../model/param';
import {Logger} from '../../utils/logger';

import Leaflet from 'leaflet';
import 'leaflet.heat';
import 'leaflet.markercluster';
import {ColorLib} from '../../utils/color-lib';
import {ChartLib} from '../../utils/chart-lib';
import {DataModel} from '../../model/dataModel';
import {MapLib} from '../../utils/map-lib';
import {GTSLib} from '../../utils/gts.lib';
import moment from 'moment-timezone';
import deepEqual from 'deep-equal';
import {SizeService} from '../../services/resize.service';

/**
 *
 */
@Component({
  selector: 'warpview-map',
  templateUrl: './warp-view-map.component.html',
  styleUrls: ['./warp-view-map.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class WarpViewMapComponent implements AfterViewInit, OnInit {

  @ViewChild('mapDiv', {static: true}) mapDiv: ElementRef<HTMLDivElement>;
  @ViewChild('wrapper', {static: true}) wrapper: ElementRef<HTMLDivElement>;
  @ViewChild('timeSlider', {static: false}) timeSlider: ElementRef<HTMLDivElement>;
  @ViewChild('timeRangeSlider', {static: false}) timeRangeSlider: ElementRef<HTMLDivElement>;

  @Input('heatData') heatData: any[] = [];
  @Input('responsive') responsive = false;
  @Input('showLegend') showLegend = true;
  @Input('width') width = ChartLib.DEFAULT_WIDTH;
  @Input('height') height = ChartLib.DEFAULT_HEIGHT;
  private bounds: any[];

  @Input('debug') set debug(debug: boolean) {
    this._debug = debug;
    this.LOG.setDebug(debug);
  }

  get debug() {
    return this._debug;
  }

  @Input('options') set options(options: Param) {
    this.LOG.debug(['onOptions'], options);
    if (!deepEqual(this._options, options)) {
      this._options = options;
      this.divider = GTSLib.getDivider(this._options.timeUnit);
      this.drawMap();
    }
  }

  @Input('data') set data(data: any) {
    this.LOG.debug(['onData'], data);
    if (data) {
      this._data = data;
      this.drawMap();
    }
  }

  get data() {
    return this._data;
  }

  @Input('hiddenData') set hiddenData(hiddenData: number[]) {
    this._hiddenData = hiddenData;
    this.drawMap();
  }

  get hiddenData(): number[] {
    return this._hiddenData;
  }

  @Output('change') change = new EventEmitter();

  currentZoom: number;
  currentLat: number;
  currentLong: number;
  minTimeValue: number;
  maxTimeValue: number;
  divider = 1;
  lowerTimeBound: number;
  upperTimeBound: number;
  timeSpan: number;
  _options: Param = new Param();

  private _firstDraw = true;
  private LOG: Logger;
  private _data: any;
  private _debug = false;
  private defOptions: Param = {
    ...new Param(), ...{
      dotsLimit: 1000,
      heatControls: false,
      timeMode: 'date',
      showRangeSelector: true,
      gridLineColor: '#8e8e8e',
      tiles: [],
      showDots: false,
      timeZone: 'UTC',
      timeUnit: 'us',
      bounds: {}
    }
  };

  private _map: Leaflet.Map;
  private _hiddenData: number[];
  private polylinesBeforeCurrentValue = [];
  private polylinesAfterCurrentValue = [];
  private currentValuesMarkers = [];
  private annotationsMarkers = [];
  private positionArraysMarkers = [];
  private _iconAnchor: Leaflet.PointExpression = [20, 52];
  private _popupAnchor: Leaflet.PointExpression = [0, -50];
  private _heatLayer: any;
  // private resizeTimer;
  private pathData: any[] = [];
  private annotationsData: any[] = [];
  private positionData: any[] = [];
  private geoJson: any[] = [];
  private parentWidth = -1;
  private timeStart: number;
  private timeEnd: number;
  private firstDraw = true;
  private finalHeight = 0;

  constructor(public el: ElementRef, public sizeService: SizeService, private renderer: Renderer2) {
    this.LOG = new Logger(WarpViewMapComponent, this.debug);
    this.LOG.debug(['constructor'], this.debug);
    this.sizeService.sizeChanged$.subscribe(() => {
      if (this._map) {
        this.resizeMe();
      }
    });
  }

  ngOnInit(): void {
    this._options = ChartLib.mergeDeep(this._options, this.defOptions) as Param;
  }

  ngAfterViewInit() {
    this.LOG.debug(['ngAfterViewInit'], this._data);
    this.drawMap();
  }

  resizeMe() {
    this.LOG.debug(['resizeMe'], this.wrapper.nativeElement.parentElement.getBoundingClientRect());
    let height = this.wrapper.nativeElement.parentElement.getBoundingClientRect().height; /* === 0
      ? ChartLib.DEFAULT_HEIGHT
      : this.el.nativeElement.parentElement.getBoundingClientRect().height; */
    const width = this.wrapper.nativeElement.parentElement.getBoundingClientRect().width; /* === 0
      ? ChartLib.DEFAULT_WIDTH
      : this.el.nativeElement.parentElement.getBoundingClientRect().width; */
    if (this._options.map.showTimeSlider && this.timeSlider && this.timeSlider.nativeElement) {
      height -= this.timeSlider.nativeElement.getBoundingClientRect().height;
    }
    if (this._options.map.showTimeRange && this.timeRangeSlider && this.timeRangeSlider.nativeElement) {
      height -= this.timeRangeSlider.nativeElement.getBoundingClientRect().height;
    }
    this.finalHeight = height;
    this.renderer.setStyle(this.mapDiv.nativeElement, 'width', 'calc(' + width + 'px - '
      + getComputedStyle(this.wrapper.nativeElement).getPropertyValue('--warp-view-map-margin').trim()
      + ' - '
      + getComputedStyle(this.wrapper.nativeElement).getPropertyValue('--warp-view-map-margin').trim()
      + ')');
    this.renderer.setStyle(this.mapDiv.nativeElement, 'height', 'calc(' + height + 'px - '
      + getComputedStyle(this.wrapper.nativeElement).getPropertyValue('--warp-view-map-margin').trim()
      + ' - '
      + getComputedStyle(this.wrapper.nativeElement).getPropertyValue('--warp-view-map-margin').trim()
      + ')');
    this.width = width;
    this.height = height;
    requestAnimationFrame(() => this._map.invalidateSize());
  }

  heatRadiusDidChange(event) {
    this._heatLayer.setOptions({radius: event.detail.valueAsNumber});
    this.LOG.debug(['heatRadiusDidChange'], event.detail.valueAsNumber);
  }

  heatBlurDidChange(event) {
    this._heatLayer.setOptions({blur: event.detail.valueAsNumber});
    this.LOG.debug(['heatBlurDidChange'], event.detail.valueAsNumber);
  }

  heatOpacityDidChange(event) {
    const minOpacity = event.detail.valueAsNumber / 100;
    this._heatLayer.setOptions({minOpacity});
    this.LOG.debug(['heatOpacityDidChange'], event.detail.valueAsNumber);
  }

  private drawMap() {
    this.LOG.debug(['drawMap'], this.data);
    this._options = ChartLib.mergeDeep(this._options, this.defOptions) as Param;
    this.timeStart = this._options.map.timeStart;
    moment.tz.setDefault(this._options.timeZone);
    let gts: any = this.data;
    if (!gts) {
      return;
    }
    if (typeof gts === 'string') {
      try {
        gts = JSON.parse(gts as string);
      } catch (error) {
        // empty
      }
    }
    if (GTSLib.isArray(gts) && gts[0] && (gts[0] instanceof DataModel || gts[0].hasOwnProperty('data'))) {
      gts = gts[0];
    }
    if (this._map) {
      this._map.invalidateSize(true);
    }
    let dataList: any[];
    let params: any[];
    if (gts.data) {
      dataList = gts.data as any[];
      this._options = ChartLib.mergeDeep(gts.globalParams || {}, this._options) as Param;
      this.timeSpan = this.timeSpan || this._options.map.timeSpan;
      params = gts.params;
    } else {
      dataList = gts;
      params = [];
    }
    this.LOG.debug(['drawMap'], dataList);
    this.LOG.debug(['drawMap'], this._options, gts.globalParams);

    const flattenGTS = GTSLib.flatDeep(dataList);
    let i = 0;
    flattenGTS.forEach(item => {
      if (item.v) {
        item.v.sort((a, b) => a[0] > b[0] ? 1 : -1);
        item.i = i;
        i++;
      }
    });
    this.LOG.debug(['GTSLib.flatDeep(dataList)'], flattenGTS);
    this.displayMap({gts: flattenGTS, params});
    this.LOG.debug(['onResize', 'postDisplayMap'], 'resizeTimer', this.el.nativeElement.parentElement.clientWidth, this.parentWidth);
    requestAnimationFrame(() => this.resizeMe());
  }

  private icon(color: string, marker = '') {
    const c = `+${color.slice(1)}`;
    const m = marker !== '' ? '-' + marker : '';
    return Leaflet.icon({
      iconUrl: 'https://api.mapbox.com/v3/marker/pin-s' + m + c + '@2x.png',
      iconAnchor: this._iconAnchor,
      popupAnchor: this._popupAnchor
    });
  }

  private displayMap(data: { gts: any[], params: any[] }) {
    this.LOG.debug(['drawMap'], data, this._options, this.hiddenData || []);
    this.divider = GTSLib.getDivider(this._options.timeUnit);
    if (!this.lowerTimeBound) {
      this.lowerTimeBound = this._options.map.timeSliderMin / this.divider;
      this.upperTimeBound = this._options.map.timeSliderMax / this.divider;
    }
    this.LOG.debug(['displayMap'], moment(this.timeStart).toISOString(), moment(this.timeEnd).toISOString());
    let height = this.height || ChartLib.DEFAULT_HEIGHT;
    const width = this.width || ChartLib.DEFAULT_WIDTH;
    if (this.responsive && this.finalHeight === 0) {
      this.resizeMe();
    } else {
      if (this._options.map.showTimeSlider && this.timeSlider && this.timeSlider.nativeElement) {
        height -= this.timeSlider.nativeElement.getBoundingClientRect().height;
      }
      if (this._options.map.showTimeRange && this.timeRangeSlider && this.timeRangeSlider.nativeElement) {
        height -= this.timeRangeSlider.nativeElement.getBoundingClientRect().height;
      }
    }
    this.width = width;
    this.height = height;
    this.pathData = MapLib.toLeafletMapPaths(data, this.hiddenData || [], this.divider, this._options.scheme) || [];
    this.annotationsData = MapLib.annotationsToLeafletPositions(data, this.hiddenData, this.divider, this._options.scheme) || [];
    this.positionData = MapLib.toLeafletMapPositionArray(data, this.hiddenData || [], this._options.scheme) || [];
    this.geoJson = MapLib.toGeoJSON(data);
    if (!this.data) {
      return;
    }
    if (this._map) {
      this._map.remove();
    }
    this.LOG.debug(['displayMap'], {
      lat: [this.currentLat, this._options.startLat],
      long: [this.currentLong, this._options.startLong],
      zoom: [this.currentZoom, this._options.startZoom]
    });
    this._map = Leaflet.map(this.mapDiv.nativeElement);

    this._map.on('load', () => {
      this.LOG.debug(['load'], this._map.getCenter().lng, this.currentLong);
      this.LOG.debug(['load'], this._map.getZoom());
    });
    this._map.on('zoomend', () => {
      if (!this.firstDraw) {
        this.currentZoom = this._map.getZoom();
      }
    });
    this._map.on('moveend', () => {
      if (!this.firstDraw) {
        this.LOG.debug(['moveend'], this._map.getCenter());
        this.currentLat = this._map.getCenter().lat;
        this.currentLong = this._map.getCenter().lng;
      }
    });
    if (this._options.map.mapType !== 'NONE') {
      const map = MapLib.mapTypes[this._options.map.mapType || 'DEFAULT'];
      const mapOpts: any = {};
      if (map.attribution) {
        mapOpts.attribution = map.attribution;
      }
      if (map.subdomains) {
        mapOpts.subdomains = map.subdomains;
      }
      Leaflet.tileLayer(map.link, mapOpts).addTo(this._map);
    }
    (this.pathData || []).forEach(d => {
      const plottedGts: any = this.updateGtsPath(d);
      if (plottedGts) {
        this.polylinesBeforeCurrentValue.push(plottedGts.beforeCurrentValue);
        this.polylinesAfterCurrentValue.push(plottedGts.afterCurrentValue);
        this.currentValuesMarkers.push(plottedGts.currentValue);
      }
    });

    (this.annotationsData || []).forEach(d => {
      //   this.annotationsMarkers = this.annotationsMarkers.concat(this.updateAnnotation(d));
      const plottedGts: any = this.updateGtsPath(d);
      if (plottedGts) {
        this.polylinesBeforeCurrentValue.push(plottedGts.beforeCurrentValue);
        this.polylinesAfterCurrentValue.push(plottedGts.afterCurrentValue);
        this.currentValuesMarkers.push(plottedGts.currentValue);
      }
    });
    this.LOG.debug(['displayMap', 'annotationsMarkers'], this.annotationsMarkers);
    this.LOG.debug(['displayMap', 'this.hiddenData'], this.hiddenData);
    // Create the positions arrays
    this.positionData.forEach(d => {
      this.positionArraysMarkers = this.positionArraysMarkers.concat(this.updatePositionArray(d));
    });

    (this._options.map.tiles || []).forEach((t) => {
      this.LOG.debug(['displayMap'], t);
      if (this._options.map.showTimeRange) {
        Leaflet.tileLayer(t
            .replace('{start}', moment(this.timeStart).toISOString())
            .replace('{end}', moment(this.timeEnd).toISOString()), {
            subdomains: 'abcd',
            maxNativeZoom: 19,
            maxZoom: 40
          }
        ).addTo(this._map);
      } else {
        Leaflet.tileLayer(t, {
          subdomains: 'abcd',
          maxNativeZoom: 19,
          maxZoom: 40
        }).addTo(this._map);
      }
    });

    this.LOG.debug(['displayMap', 'positionArraysMarkers'], this.positionArraysMarkers);
    this.positionArraysMarkers.forEach(m => {
      m.addTo(this._map);
    });

    this.annotationsMarkers.forEach(m => {
      m.addTo(this._map);
    });

    this.LOG.debug(['displayMap', 'geoJson'], this.geoJson);
    this.geoJson.forEach((m, index) => {
      const color = ColorLib.getColor(index, this._options.scheme);
      const opts = {
        style: () => ({
          color: (data.params && data.params[index]) ? data.params[index].color || color : color,
          fillColor: (data.params && data.params[index])
            ? ColorLib.transparentize(data.params[index].fillColor || color)
            : ColorLib.transparentize(color),
        })
      } as any;
      if (m.geometry.type === 'Point') {
        opts.pointToLayer = (geoJsonPoint, latlng) => Leaflet.marker(latlng, {
          icon: this.icon(color, ''),
          opacity: 1,
        });
      }
      let display = '';
      const geoShape = Leaflet.geoJSON(m, opts);
      if (m.properties) {
        Object.keys(m.properties).forEach(k => display += `<b>${k}</b>: ${m.properties[k]}<br />`);
        geoShape.bindPopup(display);
      }
      geoShape.addTo(this._map);
    });
    if (this.pathData.length > 0 || this.positionData.length > 0 || this.annotationsData.length > 0 || this.geoJson.length > 0) {
      // Fit map to curves
      this.bounds = MapLib.getBoundsArray(this.pathData, this.positionData, this.annotationsData, this.geoJson);
      requestAnimationFrame(() => {
        this._options.startZoom = this.currentZoom || this._options.startZoom || 2;
        // Without the timeout tiles doesn't show, see https://github.com/Leaflet/Leaflet/issues/694
        this._map.invalidateSize();
        if (this.bounds.length > 1) {
          this.LOG.debug(['displayMap', 'setView'], 'fitBounds');
          this._map.fitBounds(Leaflet.latLngBounds(this.bounds[0], this.bounds[1]), {
            padding: [20, 20],
            animate: false,
            duration: 0
          });
          this._map.setZoom(Math.max(this.currentZoom || this._options.startZoom, this._map.getZoom()), {
            animate: false,
            duration: 0
          });
          this.currentLat = this._map.getCenter().lat;
          this.currentLong = this._map.getCenter().lng;
        } else {
          this.LOG.debug(['displayMap', 'setView'], {lat: this.currentLat, lng: this.currentLong});
          this._map.setView({
            lat: this.currentLat || this._options.startLat || 0,
            lng: this.currentLong || this._options.startLong || 0
          }, this.currentZoom || this._options.startZoom || 10);
        }
      });
    } else {
      this.LOG.debug(['displayMap', 'lost'], 'lost', this.currentZoom, this._options.startZoom);
      this._map.setView(
        [
          this.currentLat || this._options.startLat || 0,
          this.currentLong || this._options.startLong || 0
        ],
        this.currentZoom || this._options.startZoom || 2,
        {
          animate: false,
          duration: 0
        }
      );
      window.setTimeout(() => {
        this.firstDraw = false;
      }, 1000);
    }
    if (this.heatData && this.heatData.length > 0) {
      this._heatLayer = (Leaflet as any).heatLayer(this.heatData, {
        radius: this._options.map.heatRadius,
        blur: this._options.map.heatBlur,
        minOpacity: this._options.map.heatOpacity
      });
      this._heatLayer.addTo(this._map);
    }
    this.resizeMe();
  }

  private updateGtsPath(gts: any) {
    const beforeCurrentValue = Leaflet.polyline(
      MapLib.pathDataToLeaflet(gts.path, {to: 0}), {
        color: gts.color,
        opacity: 1,
      }).addTo(this._map);
    const afterCurrentValue = Leaflet.polyline(
      MapLib.pathDataToLeaflet(gts.path, {from: 0}), {
        color: gts.color,
        opacity: 0.7,
      }).addTo(this._map);
    let currentValue;
    // Let's verify we have a path... No path, no marker
    gts.path.map(p => {
      let date;
      if (this._options.timeMode && this._options.timeMode === 'timestamp') {
        date = parseInt(p.ts, 10);
      } else {
        date = (moment(parseInt(p.ts, 10))
          .utc(true).toISOString() || '')
          .replace('Z', this._options.timeZone === 'UTC' ? 'Z' : '');
      }
      currentValue = Leaflet.circleMarker([p.lat, p.lon],
        {radius: MapLib.BASE_RADIUS, color: gts.color, fillColor: gts.color, fillOpacity: 0.7})
        .bindPopup(`<p>${date}</p><p><b>${gts.key}</b>: ${p.val.toString()}</p>`).addTo(this._map);
      return {
        beforeCurrentValue,
        afterCurrentValue,
        currentValue,
      };
    });
  }

  private addPopup(positionData: any, value: any, marker: any) {
    this.LOG.debug(['addPopup'], positionData);
    let content = '';
    if (positionData.key) {
      content = `<p><b>${positionData.key}</b>: ${value || ''}</p>`;
    }
    Object.keys(positionData.properties || []).forEach(k => content += `<b>${k}</b>: ${positionData.properties[k]}<br />`);
    marker.bindPopup(content);
  }

  private updatePositionArray(positionData: any) {
    const positions = [];
    let polyline;
    let icon;
    let result;
    let inStep;
    this.LOG.debug(['updatePositionArray'], positionData);
    switch (positionData.render) {
      case 'path':
        polyline = Leaflet.polyline(positionData.positions, {color: positionData.color, opacity: 1});
        positions.push(polyline);
        break;
      case 'marker':
        icon = this.icon(positionData.color, positionData.marker);
        positionData.positions.forEach(p => {
          if ((this.hiddenData || []).filter((i) => i === positionData.key).length === 0) {
            const marker = Leaflet.marker({lat: p[0], lng: p[1]}, {icon, opacity: 1});
            this.addPopup(positionData, p[2], marker);
            positions.push(marker);
          }
          this.LOG.debug(['updatePositionArray', 'build marker'], icon);
        });
        break;
      case 'coloredWeightedDots':
        this.LOG.debug(['updatePositionArray', 'coloredWeightedDots'], positionData);
        result = [];
        inStep = [];
        for (let j = 0; j < positionData.numColorSteps; j++) {
          result[j] = 0;
          inStep[j] = 0;
        }
        positionData.positions.forEach(p => {
          if ((this._hiddenData || []).filter((i) => i === positionData.key).length === 0) {
            this.LOG.debug(['updatePositionArray', 'coloredWeightedDots', 'radius'], positionData.baseRadius * p[4]);
            const marker = Leaflet.circleMarker(
              {lat: p[0], lng: p[1]},
              {
                radius: positionData.baseRadius * (parseInt(p[4], 10) + 1),
                color: positionData.borderColor,
                fillColor: ColorLib.rgb2hex(
                  positionData.colorGradient[p[5]].r,
                  positionData.colorGradient[p[5]].g,
                  positionData.colorGradient[p[5]].b),
                fillOpacity: 0.7,
              });
            this.addPopup(positionData, p[2], marker);
            positions.push(marker);
          }
        });
        break;
      case 'weightedDots':
        positionData.positions.forEach(p => {
          if ((this._hiddenData || []).filter((i) => i === positionData.key).length === 0) {
            const marker = Leaflet.circleMarker(
              {lat: p[0], lng: p[1]}, {
                radius: positionData.baseRadius * (parseInt(p[4], 10) + 1),
                color: positionData.borderColor,
                fillColor: positionData.color, fillOpacity: 0.7,
              });
            this.addPopup(positionData, p[2], marker);
            positions.push(marker);
          }
        });
        break;
      case 'dots':
      default:
        positionData.positions.forEach(p => {
          if ((this._hiddenData || []).filter((i) => i === positionData.key).length === 0) {
            const marker = Leaflet.circleMarker(
              {lat: p[0], lng: p[1]}, {
                radius: positionData.baseRadius,
                color: positionData.borderColor,
                fillColor: positionData.color,
                fillOpacity: 1,
              });
            this.addPopup(positionData, p[2], marker);
            positions.push(marker);
          }
        });
        break;
    }
    return positions;
  }

  public resize(): Promise<boolean> {
    return new Promise<boolean>(resolve => {
      this.resizeMe();
      resolve(true);
    });
  }

  onRangeSliderChange(event) {
    this.LOG.debug(['onRangeSliderChange'], event);
    this.timeStart = event.value || moment().valueOf();
    this.timeEnd = event.highValue || moment().valueOf();
    this.drawMap();
  }

  onRangeSliderWindowChange(event) {
    this.LOG.debug(['onRangeSliderWindowChange'], event);
    if (this.lowerTimeBound !== event.min || this.upperTimeBound !== event.max) {
      this.lowerTimeBound = event.min;
      this.upperTimeBound = event.max;
    }
  }

  onSliderChange(event) {
    this.LOG.debug(['onSliderChange'], event, moment(event.value).toISOString());
    this._firstDraw = false;
    if (this.timeEnd !== event.value) {
      this.timeSpan = this.timeSpan || this._options.map.timeSpan;
      this.timeEnd = event.value || moment().valueOf();
      this.timeStart = (event.value || moment().valueOf()) - this.timeSpan / this.divider;
      this.LOG.debug(['onSliderChange'], moment(this.timeStart).toISOString(), moment(this.timeEnd).toISOString());
      this.change.emit(this.timeStart);
      this.drawMap();
    }
  }

  updateTimeSpan(event) {
    this.LOG.debug(['updateTimeSpan'], event.target.value);
    if (this.timeSpan !== event.target.value) {
      this.timeSpan = event.target.value;
      this.timeStart = (this.timeEnd || moment().valueOf()) - this.timeSpan / this.divider;
      this.drawMap();
    }
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div class="wrapper" #wrapper (resized)="resizeMe()">
  <div class="map-container">
    <div #mapDiv></div>
    <div *ngIf="_options.map.showTimeSlider && !_options.map.showTimeRange" #timeSlider>
      <warpview-slider
        [min]="_options.map.timeSliderMin / divider" [max]="_options.map.timeSliderMax / divider"
        [value]="minTimeValue / divider"
        [step]="_options.map.timeSliderStep" [mode]="_options.map.timeSliderMode"
        (change)="onSliderChange($event)"
        [debug]="debug"
      ></warpview-slider>
    </div>
    <div *ngIf="_options.map.showTimeSlider && _options.map.showTimeRange" #timeRangeSlider>
      <!--    <warpview-range-slider *ngIf="!_options.map.timeSpan && lowerTimeBound"
                                  [min]="lowerTimeBound" [max]="upperTimeBound"
                                  [minValue]="minTimeValue / divider"
                                  [maxValue]="maxTimeValue / divider"
                                  [step]="_options.map.timeSliderStep"
                                  [mode]="_options.map.timeSliderMode"
                                  [debug]="_debug"
                                  (change)="onRangeSliderChange($event)"
           ></warpview-range-slider>-->

      <warpview-range-slider
        [min]="(_options.map.timeSliderMin / divider)" [max]="(_options.map.timeSliderMax / divider)"
        [minValue]="minTimeValue / divider"
        [maxValue]="maxTimeValue / divider"
        [mode]="_options.map.timeSliderMode"
        [debug]="debug"
        (change)="onRangeSliderWindowChange($event)"
      ></warpview-range-slider>
      <warpview-slider *ngIf="_options.map.timeSpan && lowerTimeBound"
                       [min]="lowerTimeBound" [max]="upperTimeBound"
                       [step]="(this.timeSpan || this._options.map.timeSpan) / divider"
                       [mode]="_options.map.timeSliderMode"
                       [debug]="debug"
                       (change)="onSliderChange($event)"
      ></warpview-slider>
      <div *ngIf="_options.map?.timeSpan">
        <label for="timeSpan">Timespan: </label>
        <select id="timeSpan" (change)="updateTimeSpan($event)">
          <option *ngFor="let ts of _options.map.timeSpanList" [value]="ts.value">{{ts.label}}</option>
        </select>
      </div>
    </div>
    <warpview-heatmap-sliders
      *ngIf="_options.map.heatControls"
      (heatRadiusDidChange)="heatRadiusDidChange($event)"
      (heatBlurDidChange)="heatBlurDidChange($event)"
      (heatOpacityDidChange)="heatOpacityDidChange($event)"
    ></warpview-heatmap-sliders>
  </div>

</div>

// src/components/warp-view-map/warp-view-map.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Element, Listen, Method, Prop, Watch} from '@stencil/core';

import Leaflet from 'leaflet';
import 'leaflet.heat';
import 'leaflet.markercluster';
import {ColorLib} from "../../utils/color-lib";
import {ChartLib} from "../../utils/chart-lib";
import {Logger} from "../../utils/logger";
import {DataModel} from "../../model/dataModel";
import {GTS} from "../../model/GTS";
import {MapLib} from "../../utils/map-lib";
import {Param} from "../../model/param";
import {GTSLib} from "../../utils/gts.lib";
import moment from "moment-timezone";

@Component({
  tag: 'warp-view-map',
  styleUrls: [
    '../../../node_modules/leaflet/dist/leaflet.css',
    '../../../node_modules/leaflet.markercluster/dist/MarkerCluster.css',
    '../../../node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css',
    'warp-view-map.scss'
  ],
  shadow: true
})
export class WarpViewMap {

  @Prop() width: number;
  @Prop() height: number;
  @Prop() responsive: boolean = false;
  @Prop() data: any;
  @Prop() heatData: any[] = [];
  @Prop() options: any = {};
  @Prop() hiddenData: number[] = [];
  @Prop() debug = false;

  @Element() el: HTMLElement;

  private _options: Param = {
    dotsLimit: 1000,
    heatControls: false,
    mapType: 'DEFAULT',
    timeZone: 'UTC',
    timeUnit: 'us'
  };

  private mapTypes: any = {
    DEFAULT: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    TOPO: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
    ESRI: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',
    SATELLITE: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    OCEANS: 'https://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{z}/{y}/{x}',
    GRAY: 'https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}',
    GRAYSCALE: 'https://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}',
    WATERCOLOR: 'https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png'
  };

  private _map: Leaflet.Map;
  private uuid = 'map-' + ChartLib.guid().split('-').join('');
  private LOG: Logger;
  private polylinesBeforeCurrentValue = [];
  private polylinesAfterCurrentValue = [];
  private currentValuesMarkers = [];
  private annotationsMarkers = [];
  private positionArraysMarkers = [];

  private _iconAnchor: Leaflet.PointExpression = [20, 52];
  private _popupAnchor: Leaflet.PointExpression = [0, -50];

  private _heatLayer: Leaflet.HeatLayer;
  private resizeTimer;
  private pathData: any[];
  private annotationsData: any[];
  private positionData: any[];
  private geoJson: any[];
  private tiles: any[];
  private static DEFAULT_HEIGHT: number = 600;
  private static DEFAULT_WIDTH: number = 800;
  private parentWidth = -1;
  private mapElement: HTMLElement;
  private parentHeight = -1;

  @Listen('window:resize')
  onResize() {
    if (this.el.parentElement.getBoundingClientRect().width !== this.parentWidth || this.parentWidth <= 0 || this.el.parentElement.getBoundingClientRect().height !== this.parentHeight) {
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.parentWidth = this.el.parentElement.getBoundingClientRect().width;
        this.parentHeight = this.el.parentElement.getBoundingClientRect().height;
        if (this.el.parentElement.getBoundingClientRect().width > 0) {
          this.LOG.debug(['onResize'], this.el.parentElement.getBoundingClientRect().width);
          this.drawMap();
        } else {
          this.onResize();
        }
      }, 150);
    }
  }

  @Watch('hiddenData')
  private onHideData(newValue: string[], oldValue: string[]) {
    if (newValue !== oldValue) {
      this.LOG.debug(['hiddenData'], newValue);
      this.drawMap();
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | GTS[]) {
    this.LOG.debug(['data'], newValue);
    this.drawMap();
  }

  @Watch('options')
  private onOptions(newValue: Param) {
    let optionChanged = false;
    Object.keys(newValue).forEach(opt => {
      if (this._options.hasOwnProperty(opt)) {
        optionChanged = optionChanged || (newValue[opt] !== (this._options[opt]));
      } else {
        optionChanged = true; //new unknown option
      }
    });
    if (optionChanged) {
      this.LOG.debug(['options'], newValue);
      this.drawMap();
    }
  }

  @Listen('heatRadiusDidChange')
  heatRadiusDidChange(event) {
    this._heatLayer.setOptions({radius: event.detail.valueAsNumber});
    this.LOG.debug(['heatRadiusDidChange'], event.detail.valueAsNumber);
  }

  @Listen('heatBlurDidChange')
  heatBlurDidChange(event) {
    this._heatLayer.setOptions({blur: event.detail.valueAsNumber});
    this.LOG.debug(['heatBlurDidChange'], event.detail.valueAsNumber);
  }

  @Listen('heatOpacityDidChange')
  heatOpacityDidChange(event) {
    let minOpacity = event.detail.valueAsNumber / 100;
    this._heatLayer.setOptions({minOpacity: minOpacity});
    this.LOG.debug(['heatOpacityDidChange'], event.detail.valueAsNumber);
  }

  private drawMap() {
    this.LOG.debug(['drawMap'], this.data);
    this._options = ChartLib.mergeDeep(this._options, this.options);
    moment.tz.setDefault(this._options.timeZone);
    let gts: any = this.data;
    if (!gts) {
      return;
    }
    if (typeof gts === 'string') {
      try {
        gts = JSON.parse(gts as string);
      } catch (error) {
        // empty
      }
    }
    if (GTSLib.isArray(gts) && gts[0] && (gts[0] instanceof DataModel || gts[0].hasOwnProperty('data'))) {
      gts = gts[0];
    }
    if (this._map) {
      this._map.invalidateSize(true);
    }
    let dataList: any[];
    let params: any[];
    if (gts.data) {
      dataList = gts.data as any[];
      this._options = ChartLib.mergeDeep(this._options, gts.globalParams || {});
      params = gts.params;
    } else {
      dataList = gts;
      params = [];
    }
    this.LOG.debug(['drawMap'], dataList);
    if (!dataList) {
      return;
    }
    const flattenGTS = GTSLib.flatDeep(dataList);
    let i = 0;
    flattenGTS.forEach(item => {
      if (item.v) {
        item.v.sort((a, b) => a[0] > b[0] ? 1 : -1);
        item.i = i;
        i++;
      }
    });
    this.LOG.debug(['GTSLib.flatDeep(dataList)'], flattenGTS);
    this.displayMap({gts: flattenGTS, params: params});
    this.onResize();
  }

  private icon(color, marker = '') {
    let c = "+" + color.slice(1);
    let m = marker !== '' ? '-' + marker : '';
    return Leaflet.icon({
      iconUrl: 'https://api.mapbox.com/v3/marker/pin-s' + m + c + '@2x.png',
      iconAnchor: this._iconAnchor,
      popupAnchor: this._popupAnchor
    });
  }

  private displayMap(data: { gts: any[], params: any[] }) {
    this.LOG.debug(['drawMap'], this.data, this._options, this.hiddenData);
    let divider = GTSLib.getDivider(this._options.timeUnit);
    this.pathData = MapLib.toLeafletMapPaths(data, this.hiddenData, divider);
    this.annotationsData = MapLib.annotationsToLeafletPositions(data, this.hiddenData, divider);
    this.positionData = MapLib.toLeafletMapPositionArray(data, this.hiddenData);
    this.geoJson = MapLib.toGeoJSON(data);

    if (!this.data) {
      return;
    }
    if (this._map) {
      this._map.remove();
    }
    this.mapElement = this.el.shadowRoot.querySelector('#' + this.uuid) as HTMLElement;
    const height = (this.responsive ? this.mapElement.parentElement.getBoundingClientRect().height : (this.height || WarpViewMap.DEFAULT_HEIGHT)) - 30;
    const width = (this.responsive ? this.mapElement.parentElement.getBoundingClientRect().width : this.width || WarpViewMap.DEFAULT_WIDTH);
    this.mapElement.style.width = width + 'px';
    this.mapElement.style.height = height + 'px';

    this._map = Leaflet.map(this.mapElement as HTMLElement)
      .setView([this._options.startLat || 0, this._options.startLong || 0], this._options.startZoom || 2);
    Leaflet.tileLayer(this.mapTypes[this._options.mapType || 'DEFAULT'], {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(this._map);

    this.pathData.forEach(d => {
      let plottedGts: any = this.updateGtsPath(d);
      if (plottedGts) {
        this.polylinesBeforeCurrentValue.push(plottedGts.beforeCurrentValue);
        this.polylinesAfterCurrentValue.push(plottedGts.afterCurrentValue);
        this.currentValuesMarkers.push(plottedGts.currentValue);
      }
    });

    this.annotationsData.forEach(d => {
      //   this.annotationsMarkers = this.annotationsMarkers.concat(this.updateAnnotation(d));
      let plottedGts: any = this.updateGtsPath(d);
      if (plottedGts) {
        this.polylinesBeforeCurrentValue.push(plottedGts.beforeCurrentValue);
        this.polylinesAfterCurrentValue.push(plottedGts.afterCurrentValue);
        this.currentValuesMarkers.push(plottedGts.currentValue);
      }
    });
    this.LOG.debug(['displayMap', 'annotationsMarkers'], this.annotationsMarkers);
    this.LOG.debug(['displayMap', 'this.hiddenData'], this.hiddenData);
    // Create the positions arrays
    this.positionData.forEach(d => {
      this.positionArraysMarkers = this.positionArraysMarkers.concat(this.updatePositionArray(d));
    });

    (this.tiles || []).forEach((t) => {
      Leaflet.tileLayer(t).addTo(this._map);
    },);

    this.LOG.debug(['displayMap', 'positionArraysMarkers'], this.positionArraysMarkers);
    this.positionArraysMarkers.forEach(m => {
      m.addTo(this._map);
    });

    this.annotationsMarkers.forEach(m => {
      m.addTo(this._map);
    });

    this.LOG.debug(['displayMap', 'geoJson'], this.geoJson);
    this.geoJson.forEach((m, index) => {
      const color = ColorLib.getColor(index)
      const opts = {
        style: () => ({
          color: (data.params && data.params[index]) ? data.params[index].color || color : color,
          fillColor: (data.params && data.params[index]) ? data.params[index].fillColor || ColorLib.transparentize(color) : ColorLib.transparentize(color),
        })
      } as any;
      switch (m.geometry.type) {
        case 'Point':
          opts.pointToLayer = (geoJsonPoint, latlng) => Leaflet.marker(latlng, {
            icon: this.icon(color, ''),
            opacity: 1,
          });
          break;
      }
      let display = '';
      const geoShape = Leaflet.geoJSON(m, opts);
      if (m.properties) {
        Object.keys(m.properties).forEach(k => display += `<b>${k}</b>: ${m.properties[k]}<br />`);
        geoShape.bindPopup(display);
      }
      geoShape.addTo(this._map);
    });

    if (this.pathData.length > 0 || this.positionData.length > 0 || this.annotationsData.length > 0 || this.geoJson.length > 0) {
      // Fit map to curves
      let bounds = MapLib.getBoundsArray(this.pathData, this.positionData, this.annotationsData, this.geoJson);
      window.setTimeout(() => {
        this._options.startZoom = this._options.startZoom || 2;
        // Without the timeout tiles doesn't show, see https://github.com/Leaflet/Leaflet/issues/694
        this._map.invalidateSize();
        if (bounds.length > 1) {
          this._map.fitBounds(Leaflet.latLngBounds(bounds[0], bounds[1]), {
            padding: [20, 20],
            animate: false,
            duration: 0
          });
          this._map.setZoom(Math.max(this._options.startZoom, this._map.getZoom()), {
            animate: false,
            duration: 0
          });
        } else {
          this._map.setView({
            lat: this._options.startLat || 0,
            lng: this._options.startLong || 0
          }, this._options.startZoom);
        }
      }, 1000);
    } else {

    }
    if (this.heatData && this.heatData.length > 0) {
      this._heatLayer = Leaflet.heatLayer(this.heatData, {
        radius: this._options.heatRadius,
        blur: this._options.heatBlur,
        minOpacity: this._options.heatOpacity
      });
      this._heatLayer.addTo(this._map);
    }
  }

  private updateGtsPath(gts: any) {
    let beforeCurrentValue = Leaflet.polyline(
      MapLib.pathDataToLeaflet(gts.path, {to: 0}), {
        color: gts.color,
        opacity: 1,
      }).addTo(this._map);
    let afterCurrentValue = Leaflet.polyline(
      MapLib.pathDataToLeaflet(gts.path, {from: 0}), {
        color: gts.color,
        opacity: 0.7,
      }).addTo(this._map);
    let currentValue;
    // Let's verify we have a path... No path, no marker
    gts.path.map(p => {
      let date;
      if (this._options.timeMode && this._options.timeMode === 'timestamp') {
        date = parseInt(p.ts);
      } else {
        date = (moment(parseInt(p.ts)).utc(true).toISOString() || '' ).replace('Z', this._options.timeZone == 'UTC' ? 'Z' : '');
      }
      currentValue = Leaflet.circleMarker([p.lat, p.lon],
        {radius: MapLib.BASE_RADIUS, color: gts.color, fillColor: gts.color, fillOpacity: 0.7})
        .bindPopup(`<p>${date}</p><p><b>${gts.key}</b>: ${p.val.toString()}</p>`).addTo(this._map);

      return {
        beforeCurrentValue: beforeCurrentValue,
        afterCurrentValue: afterCurrentValue,
        currentValue: currentValue,
      }
    });
  }

  private updatePositionArray(positionData: any) {
    let positions = [];
    let polyline;
    let icon;
    let result;
    let inStep;
    this.LOG.debug(['updatePositionArray'], positionData);
    switch (positionData.render) {
      case 'path':
        polyline = Leaflet.polyline(positionData.positions, {color: positionData.color, opacity: 1});
        positions.push(polyline);
        break;
      case 'marker':
        icon = this.icon(positionData.color, positionData.marker);
        for (let j = 0; j < positionData.positions.length; j++) {
          if (this.hiddenData.filter((i) => i === positionData.key).length === 0) {
            let marker = Leaflet.marker({
              lat: positionData.positions[j][0],
              lng: positionData.positions[j][1]
            }, {
              icon: icon,
              opacity: 1,
            });
            marker.bindPopup(`<p><b>${positionData.key}</b>: ${positionData.positions[j][2] || ''}</p>`);
            positions.push(marker);
          }
          this.LOG.debug(['updatePositionArray', 'build marker'], icon);
        }
        break;
      case 'coloredWeightedDots':
        this.LOG.debug(['updatePositionArray', 'coloredWeightedDots'], positionData);
        result = [];
        inStep = [];
        for (let j = 0; j < positionData.numColorSteps; j++) {
          result[j] = 0;
          inStep[j] = 0;
        }
        for (let j = 0; j < positionData.positions.length; j++) {
          if (this.hiddenData.filter((i) => i === positionData.key).length === 0) {
            this.LOG.debug(['updatePositionArray', 'coloredWeightedDots', 'radius'], positionData.baseRadius * positionData.positions[j][4]);
            let marker = Leaflet.circleMarker(
              {lat: positionData.positions[j][0], lng: positionData.positions[j][1]},
              {
                radius: positionData.baseRadius * (parseInt(positionData.positions[j][4]) + 1),
                color: positionData.borderColor,
                fillColor: ColorLib.rgb2hex(
                  positionData.colorGradient[positionData.positions[j][5]].r,
                  positionData.colorGradient[positionData.positions[j][5]].g,
                  positionData.colorGradient[positionData.positions[j][5]].b),
                fillOpacity: 0.7,
              });
            this.LOG.debug(['updatePositionArray', 'coloredWeightedDots'], marker);
            marker.bindPopup(`<p><b>${positionData.key}</b>: ${positionData.positions[j][2] || ''}</p>`);
            positions.push(marker);
          }
        }
        break;
      case 'weightedDots':
        for (let j = 0; j < positionData.positions.length; j++) {
          if (this.hiddenData.filter((i) => i === positionData.key).length === 0) {
            let marker = Leaflet.circleMarker(
              {lat: positionData.positions[j][0], lng: positionData.positions[j][1]}, {
                radius: positionData.baseRadius * (parseInt(positionData.positions[j][4]) + 1),
                color: positionData.borderColor,
                fillColor: positionData.color, fillOpacity: 0.7,
              });
            marker.bindPopup(`<p><b>${positionData.key}</b>: ${positionData.positions[j][2] || ''}</p>`);
            positions.push(marker);
          }
        }
        break;
      case 'dots':
      default:
        for (let j = 0; j < positionData.positions.length; j++) {
          if (this.hiddenData.filter((i) => i === positionData.key).length === 0) {
            let marker = Leaflet.circleMarker(
              {lat: positionData.positions[j][0], lng: positionData.positions[j][1]}, {
                radius: positionData.baseRadius,
                color: positionData.borderColor,
                fillColor: positionData.color,
                fillOpacity: 1,
              });
            marker.bindPopup(`<p><b>${positionData.key}</b>: ${positionData.positions[j][2] || ''}</p>`);
            positions.push(marker);
          }
        }
        break;
    }
    return positions;
  }

  /**
   *
   * @returns {Promise<boolean>}
   */
  @Method()
  resize(): Promise<boolean> {
    return new Promise<boolean>(resolve => {
      this.mapElement = this.el.shadowRoot.querySelector('#' + this.uuid) as any;
      const height = (this.responsive ? this.mapElement.parentElement.getBoundingClientRect().height : WarpViewMap.DEFAULT_HEIGHT) - 30;
      const width = (this.responsive ? this.mapElement.parentElement.getBoundingClientRect().width : WarpViewMap.DEFAULT_WIDTH);
      this.mapElement.style.width = width + 'px';
      this.mapElement.style.height = height + 'px';
      resolve(true);
    });
  }

  componentWillLoad() {
    this.LOG = new Logger(WarpViewMap, this.debug);
  }

  componentDidLoad() {
    this.drawMap();
    ChartLib.resizeWatchTimer(this.el, this.onResize.bind(this));
  }

  render() {
    return (
      <div class="wrapper">
        <div class="map-container">
          <div id={this.uuid}/>
        </div>
        {!!this._options.heatControls ? <warp-view-heatmap-sliders/> : ""}
      </div>
    );
  }
}
