// src/components/warp-view-gts-popup/warp-view-gts-popup.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Event, EventEmitter, Listen, Prop, State, Watch, Method} from "@stencil/core";
import {DataModel} from "../../model/dataModel";
import {ColorLib} from "../../utils/color-lib";
import {GTSLib} from "../../utils/gts.lib";
import {Logger} from "../../utils/logger";
import {GTS} from "../../model/GTS";
import {WarpViewModal} from "../warp-view-modal/warp-view-modal";
import deepEqual from "deep-equal";

@Component({
  tag: 'warp-view-gts-popup',
  styleUrl: 'warp-view-gts-popup.scss',
  shadow: true
})
export class WarpViewGtsPopup {
  @Prop() gtsList: DataModel = new DataModel();
  @Prop() maxToShow: number = 5;
  @Prop() hiddenData: number[] = [];
  @Prop() debug = false;
  @Prop() kbdLastKeyPressed:string[] = [];

  @Event() warpViewSelectedGTS: EventEmitter;

  @State() private displayed: any[] = [];
  @State() current: number = 0;

  private _gts: any[] = [];
//  private chips: HTMLElement[] = [];
  private modal: WarpViewModal;
  private modalOpenned: boolean = false;
  private LOG: Logger;

  @Listen('warpViewModalOpen')
  onWarpViewModalOpen() {
    this.modalOpenned = true;
  }

  @Listen('warpViewModalClose')
  onWarpViewModalClose() {
    this.modalOpenned = false;
  }

  @Watch('kbdLastKeyPressed')
  handleKeyDown(key: string[]) {
    if (key[0] ==='s' && !this.modalOpenned) {
      this.showPopup();
    }
    else if (this.modalOpenned) {
      switch (key[0]) {
        case'ArrowUp':
        case'j':
          this.current = Math.max(0, this.current - 1);
          this.prepareData();
          break;
        case 'ArrowDown':
        case 'k':
          this.current = Math.min(this._gts.length - 1, this.current + 1);
          this.prepareData();
          break;
        case ' ':
          this.warpViewSelectedGTS.emit({
          gts: this._gts[this.current],
          selected: this.hiddenData.indexOf(this._gts[this.current].id) > -1 
        });
          break;
        default:
          return true;
      }
    }
  }

  @Method()
  public isOpened(): boolean {
    return this.modal.isOpened();
  }

  @Watch('hiddenData')
  private onHideData(newValue: number[], oldValue: number[]) {
    this.LOG.debug(['hiddenData'], newValue);
    this.prepareData();
  }

  @Watch('gtsList')
  private onData(newValue: DataModel | GTS[], oldValue: DataModel | GTS[]) {
    this.LOG.debug(['data'], newValue);
    this.prepareData();
  }

  private showPopup() {
    this.current = 0;
    this.prepareData();
    this.modal.open();
  }

  private prepareData() {
    if (this.gtsList && this.gtsList.data) {
      this._gts = GTSLib.flatDeep([this.gtsList.data]);
      this.displayed = this._gts.slice(
        Math.max(0, Math.min(this.current - this.maxToShow, this._gts.length - 2 * this.maxToShow)),
        Math.min(this._gts.length, this.current + this.maxToShow + Math.abs(Math.min(this.current - this.maxToShow, 0)))
      ) as any[];
      this.LOG.debug(['prepareData'], this.displayed)
    }
  }

  componentWillLoad() {
    this.LOG = new Logger(WarpViewGtsPopup, this.debug);
  }

  componentDidLoad() {
    this.prepareData();
  }

  render() {
    // reusing the warp-view-chip, without passing keyboard events.
    // STENCIL BUG. mapping this.displayed should work... but including webcomponents inside slot is not working correctly at all. hence the trick to set display none.
    return <warp-view-modal kbdLastKeyPressed={this.kbdLastKeyPressed} modalTitle="GTS Selector" ref={(el: any) => {
            this.modal = el as WarpViewModal
          }}>
          {this.current > 0 ? <div class="up-arrow"/> : ''}
          <ul>
            {this._gts.map( (gts,index) => {
              return <li class={this.current == index ? 'selected' : ''} style={ this.displayed.find( g => g.id === gts.id) ? {} : { 'display':'none' }} >
                <warp-view-chip node={{gts: gts}} name={gts.c} hiddenData={this.hiddenData}/>
              </li>
            }
            )}
          </ul>
          {this.current < this._gts.length - 1 ? <div class="down-arrow"/> : ''}
          </warp-view-modal>
          
  }

}

// projects/warpview-ng/src/lib/elements/warp-view-gts-popup/warp-view-gts-popup.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {AfterViewInit, Component, EventEmitter, Input, Output, ViewChild, ViewEncapsulation} from '@angular/core';
import {DataModel} from '../../model/dataModel';
import {Logger} from '../../utils/logger';
import {GTSLib} from '../../utils/gts.lib';
import {WarpViewModalComponent} from '../warp-view-modal/warp-view-modal.component';
import {Param} from '../../model/param';
import deepEqual from 'deep-equal';
import {ChartLib} from '../../utils/chart-lib';

/**
 *
 */
@Component({
  selector: 'warpview-gts-popup',
  templateUrl: './warp-view-gts-popup.component.html',
  styleUrls: ['./warp-view-gts-popup.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewGtsPopupComponent implements AfterViewInit {
  @ViewChild('modal', {static: true}) modal: WarpViewModalComponent;

  @Input('options') set options(options: Param | string) {
    this.LOG.debug(['onOptions'], options);
    if (typeof options === 'string') {
      options = JSON.parse(options);
    }
    if (!deepEqual(options, this._options)) {
      this.LOG.debug(['options', 'changed'], options);
      this._options = ChartLib.mergeDeep(this._options, options as Param) as Param;
      this.prepareData();
    }
  }

  @Input('gtsList') set gtsList(gtsList: DataModel) {
    this._gtsList = gtsList;
    this.LOG.debug(['_gtsList'], this._gtsList);

    this.prepareData();
  }

  get gtslist(): DataModel {
    return this._gtsList;
  }

  @Input('debug') set debug(debug: boolean) {
    this._debug = debug;
    this.LOG.setDebug(debug);
  }

  get debug() {
    return this._debug;
  }

  @Input('data') set data(data: DataModel) {
    this.LOG.debug(['data'], data);
    if (data) {
      this._data = data;
    }
  }

  get data(): DataModel {
    return this._data;
  }


  @Input('hiddenData') set hiddenData(hiddenData: number[]) {
    this._hiddenData = hiddenData;
    this.prepareData();
  }

  get hiddenData(): number[] {
    return this._hiddenData;
  }

  @Input('maxToShow') maxToShow = 5;

  @Input('kbdLastKeyPressed') set kbdLastKeyPressed(kbdLastKeyPressed: string[]) {
    this._kbdLastKeyPressed = kbdLastKeyPressed;
    if (kbdLastKeyPressed[0] === 's' && !this.modalOpenned) {
      this.showPopup();
    } else if (this.modalOpenned) {
      switch (kbdLastKeyPressed[0]) {
        case'ArrowUp':
        case'j':
          this.current = Math.max(0, this.current - 1);
          this.prepareData();
          break;
        case 'ArrowDown':
        case 'k':
          this.current = Math.min(this._gts.length - 1, this.current + 1);
          this.prepareData();
          break;
        case ' ':
          this.warpViewSelectedGTS.emit({
            gts: this._gts[this.current],
            selected: this.hiddenData.indexOf(this._gts[this.current].id) > -1
          });
          break;
        default:
          return;
      }
    }
  }

  get kbdLastKeyPressed(): string[] {
    return this._kbdLastKeyPressed;
  }

  @Output('warpViewSelectedGTS') warpViewSelectedGTS = new EventEmitter<any>();
  @Output('warpViewModalOpen') warpViewModalOpen = new EventEmitter<any>();
  @Output('warpViewModalClose') warpViewModalClose = new EventEmitter<any>();

  current = 0;
  // tslint:disable-next-line:variable-name
  _gts: any[] = [];
  _options: Param = new Param();

  // tslint:disable-next-line:variable-name
  private _kbdLastKeyPressed: string[] = [];
  // tslint:disable-next-line:variable-name
  private _hiddenData: number[] = [];
  // tslint:disable-next-line:variable-name
  private _debug = false;
  // tslint:disable-next-line:variable-name
  private _gtsList: DataModel;
  // tslint:disable-next-line:variable-name
  private _data: DataModel;
  private displayed: any[] = [];
  private modalOpenned = false;
  private LOG: Logger;

  constructor() {
    this.LOG = new Logger(WarpViewGtsPopupComponent, this.debug);
  }

  ngAfterViewInit(): void {
    this.prepareData();
  }

  onWarpViewModalOpen() {
    this.modalOpenned = true;
    this.warpViewModalOpen.emit({});
  }

  onWarpViewModalClose() {
    this.modalOpenned = false;
    this.warpViewModalClose.emit({});
  }

  public isOpened(): Promise<boolean> {
    return this.modal.isOpened();
  }

  private showPopup() {
    this.current = 0;
    this.prepareData();
    this.modal.open();
  }

  public close() {
    this.modal.close();
  }

  private prepareData() {
    if (this._gtsList && this._gtsList.data) {
      this._gts = GTSLib.flatDeep([this._gtsList.data]);
      this.displayed = this._gts.slice(
        Math.max(0, Math.min(this.current - this.maxToShow, this._gts.length - 2 * this.maxToShow)),
        Math.min(this._gts.length, this.current + this.maxToShow + Math.abs(Math.min(this.current - this.maxToShow, 0)))
      ) as any[];
      this.LOG.debug(['prepareData'], this.displayed);
    }
  }

  isHidden(gts) {
    return !this.displayed.find(g => !!gts ? gts.id === g.id : false);
  }

  identify(index, item) {
    return index;
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<warpview-modal [kbdLastKeyPressed]="kbdLastKeyPressed"
                modalTitle="GTS Selector"
                #modal
                (warpViewModalClose)="onWarpViewModalClose()"
                (warpViewModalOpen)="onWarpViewModalOpen()">
  <div class="up-arrow" *ngIf="this.current > 0"></div>
  <ul>
    <li *ngFor="let g of _gts; index as index; trackBy:identify"
        [ngClass]="{ selected: current == index, hidden: isHidden(g.id) }"
    >
      <warpview-chip [node]="{gts: g}" [hiddenData]="hiddenData" [options]="_options"></warpview-chip>
    </li>
  </ul>
  <div class="down-arrow" *ngIf="current < _gts.length - 1"></div>
</warpview-modal>
