// src/components/warp-view-pie/warp-view-pie.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Element, Listen, Prop, Watch} from '@stencil/core';
import {Logger} from "../../utils/logger";
import Chart from 'chart.js';
import {Param} from "../../model/param";
import {ChartLib} from "../../utils/chart-lib";
import {ColorLib} from "../../utils/color-lib";
import {DataModel} from "../../model/dataModel";

@Component({
  tag: 'warp-view-pie',
  styleUrl: 'warp-view-pie.scss',
  shadow: true
})
export class WarpViewPie {
  @Prop() showLegend: boolean = true;
  @Prop() data: DataModel | any[];
  @Prop() options: Param = new Param();
  @Prop({mutable: true}) width = '';
  @Prop({mutable: true}) height = '';
  @Prop() responsive: boolean = false;

  @Element() el: HTMLElement;

  private LOG: Logger = new Logger(WarpViewPie);
  private _options: Param = {
    type: 'pie'
  };
  private uuid = 'chart-' + ChartLib.guid().split('-').join('');
  private _chart: Chart;
  private resizeTimer;
  private parentWidth = -1;

  @Listen('window:resize')
  onResize() {
    if(this.el.parentElement.clientWidth !== this.parentWidth) {
      this.parentWidth = this.el.parentElement.clientWidth;
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.LOG.debug(['onResize'], this.el.parentElement.clientWidth);
        this.drawChart();
      }, 250);
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | any[], oldValue: DataModel | any[]) {
    if (oldValue !== newValue) {
      this.LOG.debug(['data'], newValue);
      this.drawChart();
    }
  }

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if (oldValue !== newValue) {
      this.LOG.debug(['options'], newValue);
      this.drawChart();
    }
  }

  /**
   *
   * @param data
   * @returns {{labels: any[]; data: any[]}}
   */
  private parseData(data) {
    this.LOG.debug(['parseData'], data);
    if (!data) {
      return;
    }
    let labels = [];
    let _data = [];
    let dataList: any[];
    if (this.data instanceof DataModel) {
      dataList = this.data.data as any[];
    } else {
      dataList = this.data;
    }
    dataList.forEach(d => {
      _data.push(d[1]);
      labels.push(d[0]);
    });
    this.LOG.debug(['parseData'], [labels, _data]);
    return {labels: labels, data: _data}
  }

  private drawChart() {
    this._options = ChartLib.mergeDeep(this._options, this.options);
    let ctx = this.el.shadowRoot.querySelector("#" + this.uuid);
    let data = this.parseData(this.data);
    if (!data) {
      return;
    }
    this.height = (this.responsive ? this.el.parentElement.clientHeight : this.height || 600) + '';
    this.width = (this.responsive ? this.el.parentElement.clientWidth : this.width || 800) + '';
    this.LOG.debug(['drawChart'], [this.data, this._options, data]);
    if (this._chart) {
      this._chart.destroy();
      delete this._chart;
    }
    this.LOG.debug(['data.data'], data.data);
    if (data.data && data.data.length > 0) {
      this._options.type = this.options.type || this._options.type;
      this._chart = new Chart(ctx, {
        type: this._options.type === 'gauge' ? 'doughnut' : this._options.type,
        data: {
          datasets: [{
            data: data.data,
            backgroundColor: ColorLib.generateTransparentColors(data.data.length),
            borderColor: ColorLib.generateColors(data.data.length)
          }],
          labels: data.labels
        },
        options: {
          legend: {
            display: this.showLegend
          },
          animation: {
            duration: 0,
          },
          responsive: this.responsive,
          tooltips: {
            mode: 'index',
            intersect: true,
          },
          circumference: this.getCirc(),
          rotation: this.getRotation(),
        }
      });
      this.onResize();
    }
  }

  private getRotation() {
    if ('gauge' === this._options.type) {
      return Math.PI;
    } else {
      return -0.5 * Math.PI;
    }
  }

  private getCirc() {
    if ('gauge' === this._options.type) {
      return Math.PI;
    } else {
      return 2 * Math.PI;
    }
  }

  componentDidLoad() {
    this.drawChart();
  }

  render() {
    return <div>
      <div class="chart-container">
        <canvas id={this.uuid} width={this.width} height={this.height}/>
      </div>
    </div>;
  }
}

// projects/warpview-ng/src/lib/elements/warp-view-pie/warp-view-pie.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, ElementRef, EventEmitter, Input, OnInit, Output, ViewEncapsulation} from '@angular/core';
import {WarpViewComponent} from '../warp-view-component';
import {DataModel} from '../../model/dataModel';
import {ColorLib} from '../../utils/color-lib';
import deepEqual from 'deep-equal';
import {SizeService} from '../../services/resize.service';
import {Logger} from '../../utils/logger';
import {ChartLib} from '../../utils/chart-lib';
import {Param} from '../../model/param';

@Component({
  selector: 'warpview-pie',
  templateUrl: './warp-view-pie.component.html',
  styleUrls: ['./warp-view-pie.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewPieComponent extends WarpViewComponent implements OnInit {

  @Input('type') set type(type: string) {
    this._type = type;
    this.drawChart();
  }

  @Output('chartDraw') chartDraw = new EventEmitter<any>();

  private _type = 'pie';
  layout: Partial<any> = {
    showlegend: true,
    legend: {
      orientation: 'h',
      bgcolor: 'transparent',
    },
    orientation: 270,
    margin: {
      t: 0,
      b: 25,
      r: 0,
      l: 0
    }
  };

  update(options, refresh): void {
    this.LOG.debug(['onOptions', 'before'], this._options, options);
    if (!deepEqual(options, this._options)) {
      this.LOG.debug(['options', 'changed'], options);
      this._options = ChartLib.mergeDeep(this._options, options as Param) as Param;
    }
    this.drawChart();
  }

  constructor(
    public el: ElementRef,
    public sizeService: SizeService,
  ) {
    super(el, sizeService);
    this.LOG = new Logger(WarpViewPieComponent, this._debug);
  }

  ngOnInit(): void {
    this._options = this._options || this.defOptions;
  }

  drawChart() {
    if (!this.initChart(this.el)) {
      return;
    }
    this.LOG.debug(['drawChart', 'this.layout'], this.layout);
    this.LOG.debug(['drawChart', 'this.plotlyConfig'], this.plotlyConfig);
    this.LOG.debug(['drawChart', 'this.plotlyData'], this.plotlyData);
    this.layout.legend.font = {
      color: this.getCSSColor(this.el.nativeElement, '--warp-view-font-color', '#000')
    };
    this.layout.textfont = {
      color: this.getCSSColor(this.el.nativeElement, '--warp-view-font-color', '#000')
    };
    this.loading = false;
  }

  protected convert(data: DataModel): Partial<any>[] {
    const gtsList = data.data as any[];
    const plotData = [] as Partial<any>[];
    this.LOG.debug(['convert', 'gtsList'], gtsList);
    const pieData = {
      values: [],
      labels: [],
      marker: {
        colors: [],
        line: {
          width: 3,
          color: [],
        }
      },
      textfont: {
        color: this.getLabelColor(this.el.nativeElement)
      },
      hoverlabel: {
        bgcolor: this.getCSSColor(this.el.nativeElement, '--warp-view-chart-legend-bg', '#000000'),
        bordercolor: 'grey',
        font: {
          color: this.getCSSColor(this.el.nativeElement, '--warp-view-chart-legend-color', '#ffffff')
        }
      },
      type: 'pie'
    } as any;
    gtsList.forEach((d: any, i) => {
      const color = ColorLib.getColor(i, this._options.scheme);
      pieData.values.push(d[1]);
      pieData.labels.push(d[0]);
      pieData.marker.colors.push(ColorLib.transparentize(color));
      pieData.marker.line.color.push(color);
      if (this._type === 'donut') {
        pieData.hole = 0.5;
      }
      if (this.unit) {
        pieData.title = {
          text: this.unit
        };
      }
    });
    plotData.push(pieData);
    return plotData;
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div id="chartContainer" #chartContainer>
  <p class="noData" *ngIf="noDAta">No data to display</p>
  <warpview-spinner *ngIf="loading" message="Parsing data"></warpview-spinner>
  <div *ngIf="!loading">
    <warpview-plotly #graph *ngIf="plotlyData?.length > 0"
                 [data]="plotlyData" [layout]="layout" [config]="plotlyConfig" (afterPlot)="afterPlot()"
                 (relayout)="relayout($event)"
                 [updateOnLayoutChange]="true" [updateOnDataChange]="true" [debug]="debug"
                 [style]="{position: 'relative', width: '100%', height: '100%'}"></warpview-plotly>
  </div>
</div>
