// src/components/warp-view-tile/warp-view-tile.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Element, Listen, Method, Prop, State, Watch} from '@stencil/core';
import {GTSLib} from '../../utils/gts.lib';
import {DataModel} from "../../model/dataModel";
import {Logger} from "../../utils/logger";
import {Param} from "../../model/param";
import {ChartLib} from "../../utils/chart-lib";
import deepEqual from "deep-equal";

@Component({
  tag: 'warp-view-tile',
  styleUrl: 'warp-view-tile.scss',
  shadow: true
})
export class WarpViewTile {

  @State() data: any;
  @Prop() options: string | Param;
  @Prop() unit: string = '';
  @Prop() type: string = 'line';
  @Prop() chartTitle: string = '';
  @Prop() responsive: boolean = false;
  @Prop() showLegend: boolean = false;
  @Prop() url: string = '';
  @Prop() gtsFilter: string = '';
  @Prop() debug = false;
  @Prop() isAlone: boolean = false; //used by plot to manage its keyboard events

  @Element() wsElement: HTMLElement;

  private LOG: Logger;
  private warpScript: string = '';
  private execUrl = '';
  private timeUnit = 'us';
  private graphs = {
    'scatter': ['scatter'],
    'chart': ['line', 'spline', 'step', 'area'],
    'pie': ['pie', 'doughnut', 'gauge'],
    'polar': ['polar'],
    'radar': ['radar'],
    'bar': ['bar'],
    'annotation': ['annotation'],
    'gts-tree': ['gts-tree']
  };
  private loading = true;
  private executionErrorText: string = '';
  private gtsList: any;
  private _options: Param = new Param();
  private timer: any;
  private watchWarpScriptTimer: any;
  private _autoRefresh;

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if (!deepEqual(newValue, oldValue)) {
      this.LOG.debug(['options', 'changed'], newValue);
      this.parseGTS();
    }
  }

  @Watch('gtsFilter')
  private onGtsFilter(newValue: string, oldValue: string) {
    if (oldValue !== newValue) {
      this.parseGTS();
    }
  }

  @Method()
  resize() {
    this.execute();
  }

  @Listen('document:keyup')
  handleKeyDown(ev: KeyboardEvent) {
    if (ev.key === 'r') {
      this.execute();
    }
  }

  componentDidLoad() {
    this.execute();
  }

  componentDidUpdate() {
    window.clearInterval(this.watchWarpScriptTimer);
    this.watchWarpScriptTimer = window.setInterval(() => {
      let currentWarpScript = this.wsElement.textContent;
      if (currentWarpScript != this.warpScript) { //reference comparison, not content. content could be huge.
        this.LOG.debug(["watchSlotTimer"], "new warpscript detected");
        this.execute();
      }
    }, 1000);
  }

  private parseGTS() {
    let data: DataModel = new DataModel();
    if (GTSLib.isArray(this.gtsList) && this.gtsList.length === 1) {
      const dataLine = this.gtsList[0];
      if (dataLine.hasOwnProperty('data')) {
        data.data = dataLine.data;
        data.globalParams = dataLine.globalParams || {} as Param;
        data.globalParams.type = data.globalParams.type || this.type;
        data.params = dataLine.params;
      } else {
        data.data = dataLine;
        data.globalParams = {type: this.type} as Param;
      }
    } else {
      data.data = this.gtsList;
      data.globalParams = {type: this.type} as Param;
    }
    this.LOG.debug(['parseGTS', 'data'], data);
    this.data = data;
    let opts = new Param();
    if (typeof this.options === 'string') {
      opts = JSON.parse(this.options as string) as Param;
    } else {
      opts = this.options as Param;
    }
    this._options = ChartLib.mergeDeep(opts, data.globalParams);

    this.LOG.debug(['parseGTS', 'options'], [this.options, this._options]);
    if (this._autoRefresh !== this._options.autoRefresh) {
      this._autoRefresh = this._options.autoRefresh;
      if (this.timer) {
        window.clearInterval(this.timer);
      }
      if (this._autoRefresh && this._autoRefresh > 0) {
        this.timer = window.setInterval(() => this.execute(), this._autoRefresh * 1000);
      }
    }
    this.loading = false;
  }

  //detect some VSCode special modifiers in the beginnig of the code:
  // @endpoint xxxURLxxx
  // @timeUnit ns
  //warning : the first line is empty (to confirm with other browsers)
  private detectWarpScriptSpecialComments() {
    //
    //analyse the first warpScript lines starting with //
    //
    let warpscriptlines = this.warpScript.split('\n');
    for (let l = 1; l < warpscriptlines.length; l++) {
      let currentline = warpscriptlines[l];
      if (currentline == "" || currentline.search("//") >= 0) {
        //find and extract // @paramname parameters
        let extraparamsPattern = /\s*\/\/\s*@(\w*)\s*(.*)$/g;
        let lineonMatch: RegExpMatchArray | null;
        let re = RegExp(extraparamsPattern);
        // noinspection JSAssignmentUsedAsCondition
        while (lineonMatch = re.exec(currentline)) {
          let parameterName = lineonMatch[1];
          let parameterValue = lineonMatch[2];
          switch (parameterName) {
            case "endpoint":        //        // @endpoint http://mywarp10server/api/v0/exec
              this.execUrl = parameterValue;
              break;
            case "timeUnit":
              this.timeUnit = parameterValue.toLowerCase();   // set the time unit for graphs
              break;

            default:
              break;
          }
        }
      } else {
        break; //no more comments at the beginning of the file
      }
    }
  }


  componentWillLoad() {
    this.LOG = new Logger(WarpViewTile, this.debug);
  }

  private execute() {
    this.loading = true;
    this.warpScript = this.wsElement.textContent;
    this.LOG.debug(['execute', 'warpScript'], this.warpScript);
    this.execUrl = this.url;
    this.detectWarpScriptSpecialComments();
    fetch(this.execUrl, {method: 'POST', body: this.warpScript}).then(response => {
      if (response.status == 200) {
        response.text().then(gtsStr => {
          this.LOG.debug(['execute', 'response'], gtsStr);
          try {
            this.gtsList = JSON.parse(gtsStr);
            this.parseGTS();
          } catch (e) {
            this.LOG.error(['execute'], e);
          }
          this.loading = false;
        }, err => {
          this.LOG.error(['execute'], [err, this.url, this.warpScript]);
          this.loading = false;
        });
      } else {
        this.executionErrorText = "Execution Error : #" + response.headers.get('X-Warp10-Error-Line') + ' ' + response.headers.get('X-Warp10-Error-Message');
      }
    }, err => {
      this.LOG.error(['execute'], [err, this.url, this.warpScript]);
      this.loading = false;
      this.executionErrorText = "Failed to reach execution endpoint " + this.url;
    })
  }

  render() {
    if (this.executionErrorText != '') {
      // noinspection JSXNamespaceValidation
      return <div class="executionErrorText"> {this.executionErrorText} </div>
    } else {
      return <div class="wrapper" id="wrapper">
        <div class="warpscript">
          <slot/>
        </div>
        {this.executionErrorText != '' ? <div class="executionErrorText"> {this.executionErrorText} </div> : ''}
        {this.graphs['scatter'].indexOf(this.type) > -1 ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}</h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-scatter debug={this.debug} responsive={this.responsive} unit={this.unit} data={this.data}
                                 options={this._options} showLegend={this.showLegend}/>
            </div>
          </div>
          :
          ''
        }
        {this.graphs['chart'].indexOf(this.type) > -1 ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}</h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-chart debug={this.debug} type={this.type} responsive={this.responsive} unit={this.unit}
                               data={this.data} options={this._options} show-legend={this.showLegend}/>
            </div>
          </div>
          :
          ''
        }
        {this.type == 'bubble' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-bubble debug={this.debug} showLegend={this.showLegend} responsive={true} unit={this.unit}
                                data={this.data} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'map' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-map debug={this.debug} responsive={true} data={this.data} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.graphs['pie'].indexOf(this.type) > -1 ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-pie debug={this.debug} responsive={this.responsive} data={this.data} options={this._options}
                             showLegend={this.showLegend}/>
            </div>
          </div>
          : ''
        }
        {this.graphs['polar'].indexOf(this.type) > -1 ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-polar debug={this.debug} responsive={this.responsive} data={this.data}
                               showLegend={this.showLegend} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.graphs['radar'].indexOf(this.type) > -1 ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-radar debug={this.debug} responsive={this.responsive} data={this.data}
                               showLegend={this.showLegend} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.graphs['bar'].indexOf(this.type) > -1 ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}</h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-bar debug={this.debug} responsive={this.responsive} unit={this.unit} data={this.data}
                             showLegend={this.showLegend} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'text' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}</h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-display debug={this.debug} responsive={this.responsive} unit={this.unit} data={this.data}
                                 options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'image' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-image debug={this.debug} responsive={this.responsive} data={this.data}
                               options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'plot' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-plot debug={this.debug} responsive={this.responsive} data={this.data}
                              showLegend={this.showLegend} options={this._options} gtsFilter={this.gtsFilter}
                              isAlone={this.isAlone}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'annotation' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-annotation debug={this.debug} responsive={this.responsive} data={this.data}
                                    showLegend={this.showLegend} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'gts-tree' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-gts-tree debug={this.debug} data={this.data} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'drilldown' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-drilldown debug={this.debug} data={this.data} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.type == 'datagrid' ?
          <div class="tilewrapper">
            {(this.chartTitle && this.chartTitle !== '') ? <h1>{this.chartTitle}
              <small>{this.unit}</small>
            </h1> : ''}
            <div class={(this.chartTitle && this.chartTitle !== '') ? 'tile' : 'tile notitle'}>
              <warp-view-datagrid debug={this.debug} data={this.data} options={this._options}/>
            </div>
          </div>
          : ''
        }
        {this.loading ? <warp-view-spinner/> : ''}
      </div>
    }
  }
}

// src/app/elements/warp-view-tile/warp-view-tile.component.ts
/*
 * Copyright 2019 SenX S.A.S.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  HostListener,
  Input,
  OnInit,
  ViewChild,
  ViewEncapsulation
} from '@angular/core';
import {Param} from '../../model/param';
import {Warp10Service} from '../../services/warp10.service';
import {Logger} from '../../utils/logger';
import {ChartLib} from '../../utils/chart-lib';
import {DataModel} from '../../model/dataModel';
import {GTSLib} from '../../utils/gts.lib';
import {HttpErrorHandler} from '../../services/http-error-handler.service';
import {WarpViewComponent} from '../warp-view-component';
import {ResizedEvent} from 'angular-resize-event';
import {Size, SizeService} from '../../services/resize.service';

@Component({
  selector: 'warpview-tile',
  templateUrl: './warp-view-tile.component.html',
  styleUrls: ['./warp-view-tile.component.scss'],
  providers: [HttpErrorHandler],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewTileComponent extends WarpViewComponent implements OnInit, AfterViewInit {
  @ViewChild('warpRef') warpRef: ElementRef;
  @Input() type = 'line';
  @Input() chartTitle;
  @Input() url = '';
  @Input() isAlone = false; // used by plot to manage its keyboard events
  @Input() set gtsFilter(gtsFilter: string) {
    this._gtsFilter = gtsFilter;
    this.parseGTS();
  };

  private _gtsFilter = '';
  private warpScript = '';
  private execUrl = '';
  private timeUnit = 'us';
  graphs = {
    scatter: ['scatter'],
    chart: ['line', 'spline', 'step', 'area'],
    pie: ['pie', 'donut'],
    polar: ['polar'],
    radar: ['radar'],
    bar: ['bar'],
    bubble: ['bubble'],
    annotation: ['annotation'],
    'gts-tree': ['gts-tree'],
    datagrid: ['datagrid'],
    display: ['display'],
    drilldown: ['drilldown'],
    image: ['image'],
    map: ['map'],
    gauge: ['gauge', 'bullet'],
    plot: ['plot'],
  };
  gtsList: any = [];
  private timer: any;
  private _autoRefresh;

  /**
   *
   * @param {Warp10Service} warp10Service
   * @param {ChangeDetectorRef} cdRef
   * @param {SizeService} sizeService
   */
  constructor(private warp10Service: Warp10Service, private cdRef: ChangeDetectorRef, private sizeService: SizeService) {
    super();
    this.LOG = new Logger(WarpViewTileComponent, this._debug);
  }

  /**
   *
   */
  ngOnInit(): void {
    this._options = this._options || this.defOptions;
  }

  /**
   *
   */
  ngAfterViewInit() {
    this.warpScript = this.warpRef.nativeElement.textContent.trim();
    this.LOG.debug(['ngAfterViewInit', 'warpScript'], this.warpScript);
    this.execute();
  }

  /**
   *
   * @param {Param} options
   */
  update(options: Param): void {
    this._options = options;
    this.parseGTS();
  }

  /**
   *
   * @param {ResizedEvent} event
   */
  onResized(event: ResizedEvent) {
    this.width = event.newWidth;
    this.height = event.newHeight;
    this.LOG.debug(['onResized'], event.newWidth, event.newHeight);
    this.sizeService.change(new Size(this.width, this.height));
  }

  /* Listeners */
  @HostListener('document:keyup', ['$event'])
  @HostListener('keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent) {
    if (event.key === 'r') {
      this.execute();
    }
  }

  /**
   *
   */
  private parseGTS() {
    let data: DataModel = new DataModel();
    if (GTSLib.isArray(this.gtsList) && this.gtsList.length === 1) {
      const dataLine = this.gtsList[0];
      if (dataLine.hasOwnProperty('data')) {
        data.data = dataLine.data;
        data.globalParams = dataLine.globalParams || {} as Param;
        data.globalParams.type = data.globalParams.type || this.type;
        data.params = dataLine.params;
      } else {
        data.data = dataLine;
        data.globalParams = {type: this.type} as Param;
      }
    } else {
      data.data = this.gtsList;
      data.globalParams = {type: this.type} as Param;
    }
    this.LOG.debug(['parseGTS', 'data'], data);
    this._data = data;
    let opts = new Param();
    if (typeof this._options === 'string') {
      opts = JSON.parse(this._options as string) as Param;
    } else {
      opts = this._options as Param;
    }
    this._options = ChartLib.mergeDeep(ChartLib.mergeDeep(this.defOptions, opts), data.globalParams) as Param;

    this.LOG.debug(['parseGTS', 'options'], [this.options, this._options]);
    if (this._autoRefresh !== this._options.autoRefresh) {
      this._autoRefresh = this._options.autoRefresh;
      if (this.timer) {
        window.clearInterval(this.timer);
      }
      if (this._autoRefresh && this._autoRefresh > 0) {
        this.timer = window.setInterval(() => this.execute(), this._autoRefresh * 1000);
      }
    }
    this.loading = false;
  }

  /** detect some VSCode special modifiers in the beginnig of the code:
   * @endpoint xxxURLxxx
   * @timeUnit ns
   * warning : the first line is empty (to confirm with other browsers)
   */
  private detectWarpScriptSpecialComments() {
    //
    //analyse the first warpScript lines starting with //
    //
    let extraParamsPattern = /\s*\/\/\s*@(\w*)\s*(.*)$/g;
    let warpscriptLines = this.warpScript.split('\n');
    for (let l = 1; l < warpscriptLines.length; l++) {
      let currentLine = warpscriptLines[l];
      if (currentLine == '' || currentLine.search('//') >= 0) {
        //find and extract // @paramname parameters
        let lineOnMatch: RegExpMatchArray | null;
        let re = RegExp(extraParamsPattern);
        // noinspection JSAssignmentUsedAsCondition
        while (lineOnMatch = re.exec(currentLine)) {
          let parameterName = lineOnMatch[1];
          let parameterValue = lineOnMatch[2];
          switch (parameterName) {
            case 'endpoint':        //        // @endpoint http://mywarp10server/api/v0/exec
              this.execUrl = parameterValue;
              break;
            case 'timeUnit':
              this.timeUnit = parameterValue.toLowerCase();   // set the time unit for graphs
              break;
            default:
              break;
          }
        }
      } else {
        break; //no more comments at the beginning of the file
      }
    }
  }

  /**
   *
   */
  private execute() {
    if (this.warpScript && this.warpScript.trim() !== '') {
      this.loading = true;
      this.cdRef.detectChanges();
      this.execUrl = this.url;
      this.detectWarpScriptSpecialComments();
      this.LOG.debug(['execute', 'warpScript'], this.warpScript);
      this.warp10Service.exec(this.warpScript, this.execUrl).subscribe(gtsStr => {
        try {
          this.gtsList = gtsStr;
          this.parseGTS();
        } catch (e) {
          this.LOG.error(['execute'], e);
        }
        this.loading = false;
      });
    }
  }

  /**
   *
   * @param {DataModel} data
   * @returns {[]}
   */
  protected convert(data: DataModel): any[] {
    return [];
  }
}

<!--
  ~ Copyright 2019 SenX S.A.S.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div class="wrapper" [ngClass]="{'full':  responsive}" (resized)="onResized($event)">
  <div class="tilewrapper">
    <h1 *ngIf="chartTitle">{{chartTitle}}</h1>
    <div [ngClass]="{'tile': true,'notitle':  !chartTitle || chartTitle === ''}">
      <warpview-spinner *ngIf="loading" message="Requesting data"></warpview-spinner>

      <warpview-chart [debug]="debug" [type]="type" [unit]="unit" [options]="_options"
                      [showLegend]="showLegend" [data]="gtsList"
                      *ngIf="graphs['chart'].indexOf(type) > -1 && gtsList"
                      [responsive]="true"></warpview-chart>

      <warpview-plot [debug]="debug" [type]="type" [unit]="unit" [options]="_options"
                     [showLegend]="showLegend" [data]="gtsList"
                     *ngIf="graphs['plot'].indexOf(type) > -1 && gtsList"
                     [responsive]="true"></warpview-plot>

      <warpview-bar [debug]="debug" [unit]="unit" [options]="_options"
                    [showLegend]="showLegend" [data]="gtsList"
                    *ngIf="graphs['bar'].indexOf(type) > -1 && gtsList"
                    [responsive]="true"></warpview-bar>

      <warpview-bubble [debug]="debug" [unit]="unit" [options]="_options"
                       [showLegend]="showLegend" [data]="gtsList"
                       *ngIf="graphs['bubble'].indexOf(type) > -1 && gtsList"
                       [responsive]="true"></warpview-bubble>

      <warpview-datagrid [debug]="debug" [options]="_options"
                         [showLegend]="showLegend" [data]="gtsList"
                         *ngIf="graphs['datagrid'].indexOf(type) > -1 && gtsList"
                         [responsive]="true"></warpview-datagrid>

      <warpview-display [debug]="debug" [options]="_options"
                        [showLegend]="showLegend" [data]="gtsList" [unit]="unit"
                        *ngIf="graphs['display'].indexOf(type) > -1 && gtsList"
                        [responsive]="true"></warpview-display>

      <warpview-drill-down [debug]="debug" [options]="_options"
                           [showLegend]="showLegend" [data]="gtsList" [unit]="unit"
                           *ngIf="graphs['drilldown'].indexOf(type) > -1 && gtsList"
                           [responsive]="true"></warpview-drill-down>

      <warpview-gts-tree *ngIf="graphs['gts-tree'].indexOf(type) > -1 && gtsList"
                         [responsive]="true" [debug]="debug" [data]="gtsList" [options]="_options"></warpview-gts-tree>

      <warpview-image *ngIf="graphs['image'].indexOf(type) > -1 && gtsList"
                      [responsive]="true" [debug]="debug" [data]="gtsList" [options]="_options"></warpview-image>

      <warpview-map *ngIf="graphs['map'].indexOf(type) > -1 && gtsList" [responsive]="true" [debug]="debug"
                    [data]="gtsList" [options]="_options"></warpview-map>

      <warpview-pie [debug]="debug" [type]="type" [unit]="unit" [options]="_options"
                    [showLegend]="showLegend" [data]="gtsList"
                    *ngIf="graphs['pie'].indexOf(type) > -1 && gtsList"
                    [responsive]="true"></warpview-pie>

      <warpview-gauge [debug]="debug" [type]="type" [unit]="unit" [options]="_options"
                      [showLegend]="showLegend" [data]="gtsList"
                      *ngIf="graphs['gauge'].indexOf(type) > -1 && gtsList"
                      [responsive]="true"></warpview-gauge>

      <warpview-annotation [debug]="debug" [unit]="unit" [options]="_options"
                           [showLegend]="showLegend" [data]="gtsList"
                           *ngIf="graphs['annotation'].indexOf(type) > -1 && gtsList"
                           [responsive]="true"></warpview-annotation>

      <warpview-polar [debug]="debug" [unit]="unit" [options]="_options"
                      [showLegend]="showLegend" [data]="gtsList"
                      *ngIf="graphs['polar'].indexOf(type) > -1 && gtsList"
                      [responsive]="true"></warpview-polar>

      <warpview-radar [debug]="debug" [unit]="unit" [options]="_options"
                      [showLegend]="showLegend" [data]="gtsList"
                      *ngIf="graphs['radar'].indexOf(type) > -1 && gtsList"
                      [responsive]="true"></warpview-radar>

    </div>
  </div>
</div>
<div #warpRef style="display: none">
  <ng-content></ng-content>
</div>
