// src/app/elements/warp-view-radar/warp-view-radar.component.ts
/*
 * Copyright 2019 SenX S.A.S.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, ElementRef, EventEmitter, OnDestroy, OnInit, Output, ViewChild, ViewEncapsulation} from '@angular/core';
import {WarpViewComponent} from '../warp-view-component';
import {Logger} from '../../utils/logger';
import {Param} from '../../model/param';
import {DataModel} from '../../model/dataModel';
import {GTSLib} from '../../utils/gts.lib';
import {GTS} from '../../model/GTS';
import {ColorLib} from '../../utils/color-lib';
import * as moment from 'moment-timezone';
import deepEqual from 'deep-equal';
import {SizeService} from '../../services/resize.service';

@Component({
  selector: 'warpview-radar',
  templateUrl: './warp-view-radar.component.html',
  styleUrls: ['./warp-view-radar.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
/**
 *
 */
export class WarpViewRadarComponent extends WarpViewComponent implements OnInit, OnDestroy {

  @ViewChild('toolTip') toolTip: ElementRef;
  @ViewChild('graph') graph: ElementRef;

  @Output() chartDraw = new EventEmitter<any>();

  protected layout: Partial<any> = {
    paper_bgcolor: 'transparent',
    showlegend: true,
    legend: {orientation: 'h'},
    font: {size: 12},
    polar: {
      bgcolor: 'transparent',
      angularaxis: {
        type: 'category'
      },
      radialaxis: {
        visible: true,
      }
    }
  };

  /**
   *
   * @param {Param} options
   * @param {boolean} refresh
   */
  update(options, refresh): void {
    if (options) {
      let optionChanged = false;
      Object.keys(options).forEach(opt => {
        if (this._options.hasOwnProperty(opt)) {
          optionChanged = optionChanged || !deepEqual(options[opt] !== this._options[opt]);
        } else {
          optionChanged = true; // new unknown option
        }
      });
      if (this.LOG) {
        this.LOG.debug(['onOptions', 'optionChanged'], optionChanged);
      }
      if (optionChanged) {
        if (this.LOG) {
          this.LOG.debug(['onOptions', 'options'], options);
        }
        this._options = options;
        this.drawChart();
      }
    } else {
      this.drawChart();
    }
  }

  /**
   *
   * @param {ElementRef} el
   * @param {SizeService} sizeService
   */
  constructor(private el: ElementRef, private sizeService: SizeService) {
    super();
    this.LOG = new Logger(WarpViewRadarComponent, this._debug);
    this.sizeService.sizeChanged$.subscribe(evt => {
      if (this._chart) {
        this.layout.width = (el.nativeElement as HTMLElement).parentElement.getBoundingClientRect().width;
        this.layout.height = (el.nativeElement as HTMLElement).parentElement.getBoundingClientRect().height;
        Plotly.relayout(this.graph.nativeElement, {
          height: this.layout.height,
          width: this.layout.width
        });
      }
    });
  }

  /**
   *
   */
  ngOnInit(): void {
    this._options = this._options || this.defOptions;
  }

  /**
   *
   */
  ngOnDestroy() {
    if (this._chart) {
      Plotly.purge(this._chart);
    }
  }

  /**
   *
   */
  private drawChart() {
    if (!this.initiChart(this.el)) {
      return;
    }
    this.layout.polar.radialaxis.color = this.getGridColor(this.el.nativeElement);
    this.layout.polar.angularaxis.color = this.getGridColor(this.el.nativeElement);
    this.layout.showlegend = this.showLegend;
    this.LOG.debug(['drawChart', 'this.layout'], this.layout);
    this.LOG.debug(['drawChart', 'this.plotlyConfig'], this.plotlyConfig);
    this.LOG.debug(['drawChart', 'this.plotlyData'], this.plotlyData);
    Plotly.newPlot(this.graph.nativeElement, this.plotlyData, this.layout, this.plotlyConfig).then(plot => {
      this._chart = plot;
      this.manageTooltip(this.toolTip.nativeElement, this.graph.nativeElement);
      this.chartDraw.emit();
      this.loading = false;
    });
  }

  /**
   *
   * @param {DataModel} data
   * @returns {[]}
   */
  protected convert(data: DataModel): any[] {
    const dataset: any[] = [];
    const divider = GTSLib.getDivider(this._options.timeUnit);
    let gtsList = GTSLib.flatDeep(GTSLib.flattenGtsIdArray(data.data as any[], 0).res);
    this.LOG.debug(['convert', 'gtsList'], gtsList);
    let minVal = Number.MAX_VALUE;
    let maxVal = Number.MIN_VALUE;
    gtsList.forEach((gts: GTS) => {
      const color = ColorLib.getColor(gts.id, this._options.scheme);
      const series: any = {
        r: [],
        theta: [],
        line: {
          color: color,
        },
        marker: {
          line: {
            color: color,
            width: 1
          },
          color: ColorLib.transparentize(color)
        },
        fillcolor: ColorLib.transparentize(color),
        hoverinfo: 'none',
        name: GTSLib.serializeGtsMetadata(gts),
        text: GTSLib.serializeGtsMetadata(gts),
        type: 'scatterpolar',
        fill: 'toself'
      };
      gts.v.forEach(value => {
        const ts = value[0];
        series.r.push(value[value.length - 1]);
        minVal = Math.min(minVal, value[value.length - 1]);
        maxVal = Math.max(maxVal, value[value.length - 1]);
        if (this._options.timeMode && this._options.timeMode === 'timestamp') {
          series.theta.push(ts.toString());
        } else {
          const timestamp = Math.floor(ts / divider);
          series.theta.push(moment(timestamp).utc(true).toISOString());
        }
      });
      dataset.push(series);
    });
    this.layout.polar.radialaxis.range = [minVal, maxVal];
    return dataset;
  }
}

<!--
  ~ Copyright 2019 SenX S.A.S.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div id="chartContainer">
  <warpview-spinner *ngIf="loading" message="Parsing data"></warpview-spinner>
  <div #graph></div>
</div>
<div #toolTip class="tooltip"></div>

// src/components/warp-view-radar/warp-view-radar.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import Chart from 'chart.js';
import {Component, Element, Listen, Prop, Watch} from '@stencil/core';
import {Logger} from "../../utils/logger";
import {Param} from "../../model/param";
import {ChartLib} from "../../utils/chart-lib";
import {ColorLib} from "../../utils/color-lib";
import {DataModel} from "../../model/dataModel";
import {GTSLib} from "../../utils/gts.lib";
import deepEqual from "deep-equal";

@Component({
  tag: 'warp-view-radar',
  styleUrl: 'warp-view-radar.scss',
  shadow: true
})
export class WarpViewRadar {
  @Prop() responsive: boolean = true;
  @Prop() showLegend: boolean = true;
  @Prop() data: DataModel | any[] | string;
  @Prop() options: Param = new Param();
  @Prop({mutable: true}) width = '';
  @Prop({mutable: true}) height = '';
  @Prop() debug = false;

  @Element() el: HTMLElement;

  private LOG: Logger;
  private _options: Param = {
    gridLineColor: '#8e8e8e'
  };
  private uuid = 'chart-' + ChartLib.guid().split('-').join('');
  private _chart: Chart;
  private resizeTimer;
  private parentWidth = -1;
  private parentHeight = -1;


  @Listen('window:resize')
  onResize() {
    if (this.el.parentElement.getBoundingClientRect().width !== this.parentWidth || this.parentWidth <= 0 || this.el.parentElement.getBoundingClientRect().height !== this.parentHeight) {
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.parentWidth = this.el.parentElement.getBoundingClientRect().width;
        this.parentHeight = this.el.parentElement.getBoundingClientRect().height;
        if (this.el.parentElement.getBoundingClientRect().width > 0) {
          this.LOG.debug(['onResize'], this.el.parentElement.getBoundingClientRect().width);
          this.drawChart();
        } else {
          this.onResize();
        }
      }, 150);
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | any[]) {
    this.LOG.debug(['data'], newValue);
    this.drawChart();
  }

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if (!deepEqual(newValue, oldValue)) {
      this.LOG.debug(['options'], newValue);
      this.drawChart();
    }
  }

  private parseData(gts) {
    this.LOG.debug(['gtsToData'], gts);
    let datasets = [];
    let labels = {};

    if (!gts || gts.length === 0) {
      return;
    } else {
      let i = 0;
      gts.forEach(g => {
        Object.keys(g).forEach(label => {
          const dataSet = {
            label: label,
            data: [],
            backgroundColor: ColorLib.transparentize(ColorLib.getColor(i)),
            borderColor: ColorLib.getColor(i)
          };
          g[label].forEach(val => {
            const l = Object.keys(val)[0];
            labels[l] = 0;
            dataSet.data.push(val[l]);
          });
          datasets.push(dataSet);
          i++;
        });
      });
    }
    this.LOG.debug(['gtsToData', 'datasets'], [datasets, Object.keys(labels)]);
    return {datasets: datasets, labels: Object.keys(labels)};
  }

  private drawChart() {
    this._options = ChartLib.mergeDeep(this._options, this.options);
    let ctx = this.el.shadowRoot.querySelector('#' + this.uuid);
    this.height = (this.responsive ? this.el.parentElement.getBoundingClientRect().height : this.height || 600) + '';
    this.width = (this.responsive ? this.el.parentElement.getBoundingClientRect().width : this.width || 800) + '';
    const color = this._options.gridLineColor;
    let data: any = this.data;
    if (!data) return;
    let dataList: any[];
    if (typeof data === 'string') {
      data = JSON.parse(data as string);
    }
    if (GTSLib.isArray(data) && data[0] && (data[0] instanceof DataModel || data[0].hasOwnProperty('data'))) {
      data = data[0];
    }
    if (data instanceof DataModel || data.hasOwnProperty('data')) {
      dataList = data.data as any[];
    } else {
      dataList = data;
    }
    let gts = this.parseData(dataList);
    if (!gts) {
      return;
    }
    if (this._chart) {
      this._chart.destroy();
      delete this._chart;
    }
    this.LOG.debug(['gts.data'], gts.datasets);
    if (gts.datasets && gts.datasets.length > 0) {
      this._chart = new Chart(ctx, {
        type: 'radar',
        legend: {display: this.showLegend},
        data: {
          labels: gts.labels,
          datasets: gts.datasets
        },
        options: {
          layout: {
            padding: {
              left: 0,
              right: 0,
              top: 50,
              bottom: 0
            }
          },
          animation: {
            duration: 0,
          },
          legend: {display: this.showLegend},
          responsive: this.responsive,
          maintainAspectRatio: false,
          scale: {
            gridLines: {
              color: color,
              zeroLineColor: color
            },
            pointLabels: {
              fontColor: color,
            },
            ticks: {
              fontColor: color,
              backdropColor: 'transparent'
            }
          },
          tooltips: {
            mode: 'index',
            intersect: true,
          }
        }
      });
      this.onResize();
      setTimeout(() => {
        this._chart.update();
      }, 250);
    }
  }

  componentWillLoad() {
    this.LOG = new Logger(WarpViewRadar, this.debug);
  }

  componentDidLoad() {
    this.drawChart();
    ChartLib.resizeWatchTimer(this.el, this.onResize.bind(this));
  }

  render() {
    return <div>
      <div class="chart-container">
        <canvas id={this.uuid} width={this.width} height={this.height}/>
      </div>
    </div>;
  }
}
