// src/components/warp-view-chart/warp-view-chart.tsx
/*
 *
 *    Copyright 2016  Cityzen Data
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 */

import {Component, Element, Event, EventEmitter, Listen, Prop, Watch} from '@stencil/core';
import {GTSLib} from '../../utils/gts.lib';
import Dygraph from 'dygraphs';
import {Logger} from "../../utils/logger";
import {ChartLib} from "../../utils/chart-lib";
import {ColorLib} from "../../utils/color-lib";
import {Param} from "../../model/param";
import {DataModel} from "../../model/dataModel";
import {GTS} from "../../model/GTS";
import moment from "moment";
import Options = dygraphs.Options;

/**
 * options :
 *  gridLineColor: 'red | #fff'
 *  time.timeMode: 'timestamp | date'
 *  showRangeSelector: boolean
 *  type : 'line | area | step'
 *
 */
@Component({
  tag: 'warp-view-chart',
  styleUrls: ['../../../node_modules/dygraphs/dist/dygraph.min.css', 'warp-view-chart.scss'],
  shadow: false
})
export class WarpViewChart {
  @Prop() data: DataModel | GTS[];
  @Prop() options: Param = new Param();
  @Prop() hiddenData: string[] = [];
  @Prop() unit: string = '';
  @Prop() type: string = 'line';
  @Prop() responsive: boolean = false;
  @Prop() standalone = true;

  @Element() el: HTMLElement;

  @Event() boundsDidChange: EventEmitter;
  @Event() pointHover: EventEmitter;
  @Event() warpViewChartResize: EventEmitter;

  private LOG: Logger = new Logger(WarpViewChart);
  private static DEFAULT_WIDTH = 800;
  private static DEFAULT_HEIGHT = 600;
  private resizeTimer;
  private _chart: Dygraph;
  private _options: any = {
    time: 'date',
    showRangeSelector: true,
    gridLineColor: '#8e8e8e'
  };
  private uuid = 'chart-' + ChartLib.guid().split('-').join('');
  private ticks = [];
  private visibility: boolean[] = [];
  private showInRangeSelector: boolean[] = [];
  private initialHeight: number;

  @Watch('hiddenData')
  private onHideData(newValue: string[], oldValue: string[]) {
    if (oldValue.length !== newValue.length) {
      this.LOG.debug(['hiddenData'], newValue);
      this.drawChart();
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | GTS[], oldValue: DataModel | GTS[]) {
    if (oldValue !== newValue) {
      this.LOG.debug(['data'], newValue);
      this.drawChart();
    }
  }

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if (oldValue !== newValue) {
      this.LOG.debug(['options'], newValue);
      this.drawChart();
    }
  }

  @Listen('window:resize')
  onResize() {
    if (this._chart) {
      if(!this.initialHeight) {
        this.initialHeight = this.el.parentElement.clientHeight;
      }
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.LOG.debug(['onResize'], this.el.parentElement.clientWidth);
        const height = (this.responsive ? this.initialHeight: WarpViewChart.DEFAULT_HEIGHT) - 30;
        const width = (this.responsive ? this.el.parentElement.clientWidth : WarpViewChart.DEFAULT_WIDTH) - 5;
        this._chart.resize(width, this.displayGraph() ? height : 30);
        this.warpViewChartResize.emit({w: width, h: this.displayGraph() ? height : 30});
      }, 250);
    }
  }

  private gtsToData(gtsList) {
    this.LOG.debug(['gtsToData'], gtsList);
    this.ticks = [];
    this.visibility = [];
    const datasets = [];
    const data = {};
    let pos = 0;
    let labels = [];
    let colors = [];
    if (!gtsList) {
      return;
    } else {
      gtsList = GTSLib.flatDeep(gtsList);
      this.LOG.debug(['gtsToData', 'gtsList'], gtsList);
      labels = new Array(gtsList.length);
      labels[0] = 'Date';
      colors = new Array(gtsList.length);
      gtsList.forEach((g, i) => {
        if (g.v && GTSLib.isGtsToPlot(g)) {
          let label = GTSLib.serializeGtsMetadata(g);
          GTSLib.gtsSort(g);
          g.v.forEach(value => {
            if (!data[value[0]]) {
              data[value[0]] = new Array(gtsList.length);
              data[value[0]].fill(null);
            }
            data[value[0]][i] = value[value.length - 1] || -1;
          });
          let color = ColorLib.getColor(pos);
          labels[i + 1] = label;
          colors[i] = color;
          this.showInRangeSelector.push(true);
          this.visibility.push(this.hiddenData.filter((h) => h === label).length === 0);
        }
        pos++;
      });
    }
    labels = labels.filter((i) => !!i);
    Object.keys(data).forEach(timestamp => {
      if (this._options.timeMode && this._options.timeMode === 'timestamp') {
        datasets.push([parseInt(timestamp)].concat(data[timestamp].slice(0, labels.length - 1)));
        this.ticks.push(parseInt(timestamp));
      } else {
        const ts = Math.floor(parseInt(timestamp) / 1000);
        datasets.push([moment(ts).utc(true).toDate()].concat(data[timestamp].slice(0, labels.length - 1)));
        this.ticks.push(ts);
      }
    });
    datasets.sort((a, b) => a[0] > b[0] ? 1 : -1);
    this.LOG.debug(['gtsToData', 'datasets'], [datasets, labels, colors]);
    return {datasets: datasets, labels: labels, colors: colors.slice(0, labels.length)};
  }

  private isStepped(): boolean {
    return this.type === 'step';
  }

  private isStacked(): boolean {
    return this.type === 'area';
  }

  private legendFormatter(data) {
    if (data.x === null) {
      // This happens when there's no selection and {legend: 'always'} is set.
      return '<br>' + data.series.map(function (series) {
        if (!series.isVisible) return;
        let labeledData = series.labelHTML + ': ' + series.yHTML;
        if (series.isHighlighted) {
          labeledData = '<b>' + labeledData + '</b>';
        }
        return series.dashHTML + ' ' + labeledData;
      }).join('<br>');
    }

    let html = data.xHTML;
    data.series.forEach(function (series) {
      if (!series.isVisible || !series.yHTML) return;
      let labeledData = series.labelHTML + ': ' + series.yHTML;
      if (series.isHighlighted) {
        labeledData = '<b>' + labeledData + '</b>';
      }
      html += '<br>' + series.dashHTML + ' ' + labeledData;
    });
    return html;
  }

  private highlightCallback(event) {
    this.LOG.debug(['highlightCallback', 'event'], [this.el, event]);
    this.pointHover.emit({
      x: event.offsetX,
      y: event.offsetY
    });
  }

  private drawChart() {
    this.LOG.debug(['drawChart', 'this.data'], [this.data]);
    this._options = ChartLib.mergeDeep(this._options, this.options);
    let dataList = GTSLib.getData(this.data).data;

    const dataToplot = this.gtsToData(dataList);
    this.LOG.debug(['drawChart', 'dataToplot'], dataToplot);
    const chart = this.el.querySelector('#' + this.uuid) as HTMLElement;
    if (dataToplot) {
      const color = this._options.gridLineColor;
      let options: Options = {
        height: this.displayGraph() ? (this.responsive ? this.el.parentElement.clientHeight : WarpViewChart.DEFAULT_HEIGHT) - 30 : 30,
        width: (this.responsive ? this.el.parentElement.clientWidth : WarpViewChart.DEFAULT_WIDTH) - 5,
        labels: dataToplot.labels,
        showRoller: false,
        showRangeSelector: this._options.showRangeSelector || true,
        showInRangeSelector: true,
        connectSeparatedPoints: true,
        colors: dataToplot.colors,
        legend: 'follow',
        stackedGraph: this.isStacked(),
        strokeBorderWidth: this.isStacked() ? null : 0,
        strokeWidth: 2,
        stepPlot: this.isStepped(),
        ylabel: this.unit,
        labelsSeparateLines: true,
        highlightSeriesBackgroundAlpha: 1,
        highlightSeriesOpts: {
          strokeWidth: 3,
          strokeBorderWidth: 0,
          highlightCircleSize: 3,
          showInRangeSelector: true
        },
        visibility: this.visibility,
        hideOverlayOnMouseOut: true,
        labelsUTC: true,
        gridLineColor: color,
        axisLineColor: color,
        axes: {
          x: {
            drawAxis: this.displayGraph()
          }
        },
        legendFormatter: this.legendFormatter,
        highlightCallback: this.highlightCallback.bind(this),
        drawCallback: ((dygraph, is_initial) => {
          this.LOG.debug(['drawCallback'], [dygraph.dateWindow_, is_initial]);
          if (dygraph.dateWindow_) {
            this.boundsDidChange.emit({
              bounds: {
                min: dygraph.dateWindow_[0],
                max: dygraph.dateWindow_[1]
              }
            });
          } else {
            this.boundsDidChange.emit({
              bounds: {
                min: Math.min.apply(null, this.ticks),
                max: Math.max.apply(null, this.ticks)
              }
            });
          }
        }).bind(this),
        axisLabelWidth: this.standalone ? 50 : 94,
        rightGap: this.standalone ? 0 : 20
      };
      if (!this.displayGraph()) {
        options.xAxisHeight = 30;
        options.rangeSelectorHeight = 30;
        chart.style.height = '30px';
      }
      this._chart = new Dygraph(
        chart,
        dataToplot.datasets || [],
        options
      );
      this.onResize();
    }
  }

  private displayGraph() {
    let status = false;
    this.visibility.forEach(s => {
      status = s || status;
    });
    return status;
  }

  componentDidLoad() {
    this.drawChart();
  }

  render() {
    return <div>
      <div id={this.uuid} class="chart"/>
    </div>;
  }
}

// src/app/elements/warp-view-chart/warp-view-chart.component.ts
/*
 * Copyright 2019 SenX S.A.S.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, ElementRef, EventEmitter, Input, OnDestroy, OnInit, Output, ViewChild, ViewEncapsulation} from '@angular/core';
import {DataModel} from '../../model/dataModel';
import {GTS} from '../../model/GTS';
import {Param} from '../../model/param';
import {GTSLib} from '../../utils/gts.lib';
import * as moment from 'moment-timezone';
import {ChartBounds} from '../../model/chartBounds';
import deepEqual from 'deep-equal';
import {ColorLib} from '../../utils/color-lib';
import {Logger} from '../../utils/logger';
import {WarpViewComponent} from '../warp-view-component';
import {SizeService} from '../../services/resize.service';

type visibilityState = 'unknown' | 'nothingPlottable' | 'plottablesAllHidden' | 'plottableShown';

@Component({
  selector: 'warpview-chart',
  templateUrl: './warp-view-chart.component.html',
  styleUrls: ['./warp-view-chart.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewChartComponent extends WarpViewComponent implements OnInit, OnDestroy {
  @ViewChild('toolTip') toolTip: ElementRef;
  @ViewChild('graph') graph: ElementRef;

  @Input() set hiddenData(hiddenData: number[]) {
    const previousVisibility = JSON.stringify(this.visibility);
    this._hiddenData = hiddenData;
    if (!!this._chart) {
      this.visibility = [];
      this.visibleGtsId.forEach(id => {
        this.visibility.push(hiddenData.indexOf(id) < 0 && (id !== -1));
      });
      this.LOG.debug(['hiddenData', 'hiddendygraphfullv'], this.visibility);
    }
    const newVisibility = JSON.stringify(this.visibility);
    if (previousVisibility !== newVisibility) {
      this.drawChart(false);
      this.LOG.debug(['hiddendygraphtrig', 'destroy'], 'redraw by visibility change');
    }
  }

  @Input() set type(type: string) {
    this._type = type;
    this.drawChart();
  }

  @Input() standalone = true;
  @Output() boundsDidChange = new EventEmitter<any>();
  @Output() pointHover = new EventEmitter<any>();
  @Output() warpViewChartResize = new EventEmitter<any>();
  @Output() chartDraw = new EventEmitter<any>();

  private _type = 'line';
  private visibility: boolean[] = [];

  protected layout: Partial<any> = {
    showlegend: false,
    autosize: true,
    xaxis: {
      rangeslider: {
        bgcolor: 'transparent'
      }
    },
    yaxis: {
      exponentformat: 'none',
      fixedrange: true,
      showline: true
    },
    margin: {
      t: 0,
      b: 25,
      r: 0,
      l: 50
    },
  };

  /**
   * usefull for default zoom
   */
  private maxTick = 0;
  /**
   * usefull for default zoom
   */
  private minTick = 0;
  /**
   * table of gts id displayed in dygraph. array order is the one of dygraph series
   */
  private visibleGtsId = [];
  /**
   * key = timestamp. values = table of available points, filled by null.
   */
  private dataHashset = {};
  /**
   * contains the bounds of current graph, in timestamp (platform time unit), and in millisecond.
   */
  private chartBounds: ChartBounds = new ChartBounds();
  private visibilityStatus: visibilityState = 'unknown';

  /**
   *
   * @param {Param} options
   * @param {boolean} refresh
   */
  update(options, refresh): void {
    this.drawChart(refresh);
  /*  if (options) {
      this.visibilityStatus = 'unknown';
      let optionChanged = false;
   /!*   Object.keys(options).forEach(opt => {
        if (this._options.hasOwnProperty(opt)) {
          optionChanged = optionChanged || !deepEqual(options[opt] !== this._options[opt]);
        } else {
          optionChanged = true; // new unknown option
        }
      });*!/
      if (this.LOG) {
        this.LOG.debug(['onOptions', 'optionChanged'], optionChanged);
      }
    /!*  if (optionChanged) {
        if (this.LOG) {
          this.LOG.debug(['onOptions', 'options'], options);
        }*!/
        this._options = options;
        this.drawChart(false);
      //}
    } else {
      this.drawChart(refresh);
    }*/
  }

  /**
   *
   * @param {ElementRef} el
   * @param {SizeService} sizeService
   */
  constructor(private el: ElementRef, private sizeService: SizeService) {
    super();
    this.LOG = new Logger(WarpViewChartComponent, this._debug);
    this.sizeService.sizeChanged$.subscribe(() => {
      if (this._chart) {
        this.layout.width = (el.nativeElement as HTMLElement).parentElement.getBoundingClientRect().width;
        this.layout.height = (el.nativeElement as HTMLElement).parentElement.getBoundingClientRect().height;
        this.layout.xaxis.rangeslider.thickness = 40 / this.layout.height;
        Plotly.relayout(this.graph.nativeElement, {
          height: this.layout.height,
          width: this.layout.width,
          xaxis: {
            rangeslider: {
              thickness: 40 / this.layout.height
            }
          }
        });
      }
    });
  }

  /**
   *
   */
  ngOnInit(): void {
    this._options = this._options || this.defOptions;
  }

  /**
   *
   */
  ngOnDestroy() {
    if (this._chart) {
      this._chart.removeAllListeners('plotly_hover');
      this._chart.removeAllListeners('plotly_unhover');
      this._chart.removeAllListeners('plotly_relayout');
      Plotly.purge(this._chart);
    }
  }

  /**
   *
   * @returns {Promise<ChartBounds>}
   */
  public async getTimeClip(): Promise<ChartBounds> {
    return new Promise<ChartBounds>(resolve => {
      this.LOG.debug(['getTimeClip'], this.chartBounds);
      resolve(this.chartBounds);
    });
  }

  /**
   *
   * @param {number} newHeight
   */
  public resize(newHeight: number) {
    this.height = newHeight;
    this.layout.height = this.height;
    this.layout.xaxis.rangeslider.thickness = 40 / this.layout.height;
    Plotly.relayout(this.graph.nativeElement, {
      height: this.layout.height,
      xaxis: {
        rangeslider: {
          thickness: 40 / this.layout.height
        }
      }
    });
  }

  /**
   *
   * @param {boolean} reparseNewData
   */
  drawChart(reparseNewData: boolean = false) {
    if (!this.initiChart(this.el)) {
      return;
    }
    this.plotlyConfig.scrollZoom = true;
    if (this._options.timeMode && this._options.timeMode === 'timestamp') {
      this.layout.xaxis.tick0 = this.minTick / this.divider;
    } else {
      this.layout.xaxis.tick0 = moment.tz(this.minTick / this.divider, this._options.timeZone).toISOString(true);
    }

    this.layout.yaxis.color = this.getGridColor(this.el.nativeElement);
    this.layout.xaxis.color = this.getGridColor(this.el.nativeElement);
    if (!this.responsive) {
      this.layout.width = this.width;
      this.layout.height = this.height;
    }
    this.LOG.debug(['drawChart', 'this.layout'], this.responsive, reparseNewData);
    this.LOG.debug(['drawChart', 'this.layout'], this.layout);
    this.LOG.debug(['drawChart', 'this.plotlyConfig'], this.plotlyConfig);
    if (this._chart) {
      this.ngOnDestroy();
    }
    this.layout.xaxis.rangeslider.thickness = 40 / this.height;
    Plotly.newPlot(this.graph.nativeElement, this.plotlyData, this.layout, this.plotlyConfig).then(plot => {
      this._chart = plot;
      this.manageTooltip(this.toolTip.nativeElement, this.graph.nativeElement);
      this._chart.on('plotly_relayout', data => {
        this.LOG.debug(['plotly_relayout'], data);
        if (data['xaxis.range'] && data['xaxis.range'].length === 2) {
          this.emitNewBounds(data['xaxis.range'][0], data['xaxis.range'][1]);
        } else if (data['xaxis.range[0]'] && data['xaxis.range[1]']) {
          this.emitNewBounds(data['xaxis.range[0]'], data['xaxis.range[1]']);
        } else if (data['xaxis.autorange']) {
          this.emitNewBounds(this.minTick / this.divider, this.maxTick / this.divider);
        }
      });
      this.chartDraw.emit();
      this.emitNewBounds(this.minTick / this.divider, this.maxTick / this.divider);
      this.loading = false;
    });
  }

  /**
   *
   * @param min
   * @param max
   */
  private emitNewBounds(min, max) {
    if (this._options.timeMode && this._options.timeMode === 'timestamp') {
      this.boundsDidChange.emit({
        bounds: {
          min: min,
          max: max,
        }
      });
    } else {
      this.boundsDidChange.emit({
        bounds: {
          min: moment.tz(min, this._options.timeZone).valueOf(),
          max: moment.tz(max, this._options.timeZone).valueOf()
        }
      });
    }
  }

  /**
   *
   * @param {DataModel} data
   * @returns {Partial<>[]}
   */
  protected convert(data: DataModel): Partial<any>[] {
    const dataset: Partial<any>[] = [];
    this.LOG.debug(['convert'], this._options.timeMode);
    this.visibility = [];
    let gtsList = GTSLib.flatDeep(GTSLib.flattenGtsIdArray(data.data as any[], 0).res);
    this.maxTick = Number.NEGATIVE_INFINITY;
    this.minTick = Number.POSITIVE_INFINITY;
    this.visibleGtsId = [];
    const nonPlottable = gtsList.filter(g => {
      return (g.v && !GTSLib.isGtsToPlot(g));
    });
    gtsList = gtsList.filter(g => {
      return (g.v && GTSLib.isGtsToPlot(g));
    });
    // initialize visibility status
    if (this.visibilityStatus === 'unknown') {
      this.visibilityStatus = gtsList.length > 0 ? 'plottableShown' : 'nothingPlottable';
    }

    if (this._options.timeMode && this._options.timeMode === 'timestamp') {
      this.layout.xaxis.type = 'linear';
    } else {
      this.layout.xaxis.type = 'date';
    }
    gtsList.forEach((gts: GTS) => {
      if (gts.v && GTSLib.isGtsToPlot(gts)) {
        const label = GTSLib.serializeGtsMetadata(gts);
        const color = ColorLib.getColor(gts.id, this._options.scheme);
        console.log(color)
        const series: Partial<any> = {
          type: 'scatter',
          mode: this._options.showDots ? 'lines+markers' : 'lines',
          name: label,
          text: label,
          x: [],
          y: [],
          line: {color: color},
          hoverinfo: 'none',
          connectgaps: false,
          visible: this._hiddenData.filter(h => h === gts.id).length >= 0,
          // 'line.color': color,
        };
        switch (this._type) {
          case 'spline':
            series.line.shape = 'spline';
            break;
          case 'area':
            series.fill = 'tozeroy';
            break;
          case 'step':
            series.line.shape = 'hvh';
            break;
          case 'step-before':
            series.line.shape = 'vh';
            break;
          case 'step-after':
            series.line.shape = 'hv';
            break;
        }
        this.visibility.push(true);
        this.visibleGtsId.push(gts.id);

        gts.v.forEach(value => {
          const ts = value[0];
          if (ts < this.minTick) {
            this.minTick = ts;
          }
          if (ts > this.maxTick) {
            this.maxTick = ts;
          }
          (series.y as any[]).push(value[value.length - 1]);
          if (this._options.timeMode && this._options.timeMode === 'timestamp') {
            (series.x as any).push(ts);
          } else {
            (series.x as any).push(moment(Math.floor(ts / this.divider)).utc(true).toDate());
          }
        });
        dataset.push(series);
      }
    });
    if (nonPlottable.length > 0) { // && gtsList.length === 0) {
      nonPlottable.forEach(g => {
        g.v.forEach(value => {
          const ts = value[0];
          if (ts < this.minTick) {
            this.minTick = ts;
          }
          if (ts > this.maxTick) {
            this.maxTick = ts;
          }
        });
      });
      // if there is not any plottable data, we must add a fake one with id -1. This one will always be hidden.
      if (0 === gtsList.length) {
        if (!this.dataHashset[this.minTick]) {
          this.dataHashset[this.minTick] = [0];
        }
        if (!this.dataHashset[this.maxTick]) {
          this.dataHashset[this.maxTick] = [0];
        }
        this.visibility.push(false);
        this.visibleGtsId.push(-1);
      }
    }

    return dataset;
  }
}

<!--
  ~ Copyright 2019 SenX S.A.S.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div id="chartContainer">
  <warpview-spinner *ngIf="loading" message="Parsing data"></warpview-spinner>
  <div #graph class="chart"></div>
</div>
<div #toolTip class="tooltip"></div>
