// src/components/warp-view-pie/warp-view-pie.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Element, Listen, Prop, Watch} from '@stencil/core';
import {Logger} from "../../utils/logger";
import Chart from 'chart.js';
import {Param} from "../../model/param";
import {ChartLib} from "../../utils/chart-lib";
import {ColorLib} from "../../utils/color-lib";
import {DataModel} from "../../model/dataModel";
import {GTSLib} from "../../utils/gts.lib";
import deepEqual from "deep-equal";

@Component({
  tag: 'warp-view-pie',
  styleUrl: 'warp-view-pie.scss',
  shadow: true
})
export class WarpViewPie {
  @Prop() showLegend: boolean = true;
  @Prop() data: DataModel | any[] | string;
  @Prop() options: Param = new Param();
  @Prop({mutable: true}) width = '';
  @Prop({mutable: true}) height = '';
  @Prop() responsive: boolean = false;
  @Prop() debug = false;

  @Element() el: HTMLElement;

  private LOG: Logger;
  private _options: Param = {
    type: 'pie'
  };
  private uuid = 'chart-' + ChartLib.guid().split('-').join('');
  private _chart: Chart;
  private resizeTimer;
  private parentWidth = -1;

  @Listen('window:resize')
  onResize() {
    if (this.el.parentElement.clientWidth !== this.parentWidth) {
      this.parentWidth = this.el.parentElement.clientWidth;
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.LOG.debug(['onResize'], this.el.parentElement.clientWidth);
        this.drawChart();
      }, 250);
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | any[], oldValue: DataModel | any[]) {
    if (!deepEqual(newValue, oldValue)) {
      this.LOG.debug(['data'], newValue);
      this.drawChart();
    }
  }

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if (!deepEqual(newValue, oldValue)) {
      this.LOG.debug(['options'], newValue);
      this.drawChart();
    }
  }

  /**
   *
   * @param data
   * @returns {{labels: any[]; data: any[]}}
   */
  private parseData(data) {
    this.LOG.debug(['parseData'], data);
    if (!data) {
      return;
    }
    let labels = [];
    let _data = [];
    let dataList: any[];
    if (typeof data === 'string') {
      data = JSON.parse(data as string);
    }
    if (GTSLib.isArray(data) && data[0] && (data[0] instanceof DataModel || data[0].hasOwnProperty('data'))) {
      data = data[0];
    }
    if (data instanceof DataModel || data.hasOwnProperty('data')) {
      dataList = data.data as any[];
      this._options = ChartLib.mergeDeep(this._options, data.globalParams || {});
    } else {
      dataList = data;
    }
    if (!dataList) {
      return {labels: [], data: []}
    } else {
      dataList.forEach(d => {
        _data.push(d[1]);
        labels.push(d[0]);
      });
      this.LOG.debug(['parseData'], [labels, _data]);
      return {labels: labels, data: _data}
    }
  }

  private drawChart() {
    this._options = ChartLib.mergeDeep(this._options, this.options);
    let ctx = this.el.shadowRoot.querySelector("#" + this.uuid);
    let data = this.parseData(this.data);
    if (!data) {
      return;
    }
    this.height = (this.responsive ? this.el.parentElement.clientHeight : this.height || 600) + '';
    this.width = (this.responsive ? this.el.parentElement.clientWidth : this.width || 800) + '';
    this.LOG.debug(['drawChart'], [this.data, this._options, data]);
    if (this._chart) {
      this._chart.destroy();
      delete this._chart;
    }
    this.LOG.debug(['data.data'], data.data);
    if (data.data && data.data.length > 0) {
      this._options.type = this.options.type || this._options.type;
      this._chart = new Chart(ctx, {
        type: this._options.type === 'gauge' ? 'doughnut' : this._options.type,
        data: {
          datasets: [{
            data: data.data,
            backgroundColor: ColorLib.generateTransparentColors(data.data.length),
            borderColor: ColorLib.generateColors(data.data.length)
          }],
          labels: data.labels
        },
        options: {
          legend: {
            display: this.showLegend
          },
          animation: {
            duration: 0,
          },
          responsive: this.responsive,
          tooltips: {
            mode: 'index',
            intersect: true,
          },
          circumference: this.getCirc(),
          rotation: this.getRotation(),
        }
      });
      this.onResize();
    }
  }

  private getRotation() {
    if ('gauge' === this._options.type) {
      return Math.PI;
    } else {
      return -0.5 * Math.PI;
    }
  }

  private getCirc() {
    if ('gauge' === this._options.type) {
      return Math.PI;
    } else {
      return 2 * Math.PI;
    }
  }

  componentWillLoad() {
    this.LOG = new Logger(WarpViewPie, this.debug);
  }

  componentDidLoad() {
    this.drawChart();
  }

  render() {
    return <div>
      <div class="chart-container">
        <canvas id={this.uuid} width={this.width} height={this.height}/>
      </div>
    </div>;
  }
}

// src/app/elements/warp-view-pie/warp-view-pie.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, ElementRef, EventEmitter, Input, OnDestroy, OnInit, Output, ViewChild, ViewEncapsulation} from '@angular/core';
import {WarpViewComponent} from '../warp-view-component';
import {Logger} from '../../utils/logger';
import {DataModel} from '../../model/dataModel';
import {ColorLib} from '../../utils/color-lib';
import {SizeService} from '../../services/resize.service';
import deepEqual from 'deep-equal';
import Plotly from 'plotly.js';

@Component({
  selector: 'warpview-pie',
  templateUrl: './warp-view-pie.component.html',
  styleUrls: ['./warp-view-pie.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewPieComponent extends WarpViewComponent implements OnInit, OnDestroy {
  @ViewChild('graph', {static: true}) graph: ElementRef;
  @ViewChild('toolTip', {static: false}) toolTip: ElementRef;

  @Input('type') set type(type: string) {
    this._type = type;
    this.drawChart();
  }

  @Output('chartDraw') chartDraw = new EventEmitter<any>();

  private _type = 'pie';
  protected layout: Partial<any> = {
    showlegend: true,
    legend: {
      orientation: 'h',
      bgcolor: 'transparent',
    },
    orientation: 270
  };

  update(options, refresh): void {
    if (options) {
      let optionChanged = false;
      Object.keys(options).forEach(opt => {
        if (this._options.hasOwnProperty(opt)) {
          optionChanged = optionChanged || !deepEqual(options[opt], this._options[opt]);
        } else {
          optionChanged = true; // new unknown option
        }
      });
      if (this.LOG) {
        this.LOG.debug(['onOptions', 'optionChanged'], optionChanged);
      }
      if (optionChanged) {
        if (this.LOG) {
          this.LOG.debug(['onOptions', 'options'], options);
        }
        this._options = options;
        this.drawChart();
      }
    } else {
      this.drawChart();
    }
  }

  constructor(private el: ElementRef, private sizeService: SizeService) {
    super();
    this.LOG = new Logger(WarpViewPieComponent, this._debug);
    this.sizeService.sizeChanged$.subscribe(evt => {
      if (this._chart) {
        this.layout.width = (el.nativeElement as HTMLElement).parentElement.getBoundingClientRect().width;
        this.layout.height = (el.nativeElement as HTMLElement).parentElement.getBoundingClientRect().height;
        Plotly.relayout(this.graph.nativeElement, {
          height: this.layout.height,
          width: this.layout.width
        });
      }
    });
  }

  ngOnInit(): void {
    this._options = this._options || this.defOptions;
  }

  ngOnDestroy() {
    if (this._chart) {
      Plotly.purge(this._chart);
    }
  }

  drawChart() {
    if (!this.initiChart(this.el)) {
      return;
    }
    this.LOG.debug(['drawChart', 'this.layout'], this.layout);
    this.LOG.debug(['drawChart', 'this.plotlyConfig'], this.plotlyConfig);
    this.LOG.debug(['drawChart', 'this.plotlyData'], this.plotlyData);
    this.layout.legend.font = {
      color: this.getCSSColor(this.el.nativeElement, '--warp-view-font-color', '#000')
    };
    this.layout.textfont = {
      color: this.getCSSColor(this.el.nativeElement, '--warp-view-font-color', '#000')
    };
    Plotly.newPlot(this.graph.nativeElement, this.plotlyData, this.layout, this.plotlyConfig).then(plot => {
      this.loading = false;
      this._chart = plot;
      this.chartDraw.emit();
    });
  }

  protected convert(data: DataModel): Partial<any>[] {
    const gtsList = data.data as any[];
    const plotData = [] as Partial<any>[];
    this.LOG.debug(['convert', 'gtsList'], gtsList);
    const pieData = {
      values: [],
      labels: [],
      marker: {
        colors: [],
        line: {
          width: 3,
          color: [],
        }
      },
      textfont: {
        color: this.getLabelColor(this.el.nativeElement)
      },
      hoverlabel: {
        bgcolor: this.getCSSColor(this.el.nativeElement, '--warp-view-chart-legend-bg', '#000000'),
        bordercolor: 'grey',
        font: {
          color: this.getCSSColor(this.el.nativeElement, '--warp-view-chart-legend-color', '#ffffff')
        }
      },
      type: 'pie'
    } as any;
    gtsList.forEach((d: any, i) => {
      const color = ColorLib.getColor(i, this._options.scheme);
      pieData.values.push(d[1]);
      pieData.labels.push(d[0]);
      pieData.marker.colors.push(ColorLib.transparentize(color));
      pieData.marker.line.color.push(color);
      if (this._type === 'donut') {
        pieData.hole = 0.5;
      }
      if (this.unit) {
        pieData.title = {
          text: this.unit
        };
      }
    });
    plotData.push(pieData);
    return plotData;
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div id="chartContainer">
  <warpview-spinner *ngIf="loading" message="Parsing data"></warpview-spinner>
  <div #graph></div>
</div>
