// projects/warpview-ng/src/lib/elements/warp-view-drill-down/warp-view-drill-down.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {AfterViewInit, Component, ElementRef, HostListener, ViewEncapsulation} from '@angular/core';
import {WarpViewComponent} from '../warp-view-component';
import {Param} from '../../model/param';
import moment from 'moment';
import {GTSLib} from '../../utils/gts.lib';
import {ColorLib} from '../../utils/color-lib';
import {DataModel} from '../../model/dataModel';
import {SizeService} from '../../services/resize.service';
import {Logger} from '../../utils/logger';

/**
 *
 */
@Component({
  selector: 'warpview-drill-down',
  templateUrl: './warp-view-drill-down.component.html',
  styleUrls: ['./warp-view-drill-down.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewDrillDownComponent extends WarpViewComponent implements AfterViewInit {

  heatMapData: any;
  private parentWidth = -1;
  private resizeTimer;

  constructor(
    public el: ElementRef,
    public sizeService: SizeService,
  ) {
    super(el, sizeService);
    this.LOG = new Logger(WarpViewDrillDownComponent, this._debug);
  }

  ngAfterViewInit() {
    this.drawChart();
  }

  update(options: Param, refresh: boolean): void {
    this.drawChart();
  }

  @HostListener('window:resize')
  onResize() {
    if (this.el.nativeElement.parentElement.clientWidth !== this.parentWidth || this.parentWidth <= 0) {
      this.parentWidth = this.el.nativeElement.parentElement.clientWidth;
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        if (this.el.nativeElement.parentElement.clientWidth > 0) {
          this.LOG.debug(['onResize'], this.el.nativeElement.parentElement.clientWidth);
          this.drawChart();
        } else {
          this.onResize();
        }
      }, 150);
    }
  }

  private drawChart() {
    if (!this.initChart(this.el)) {
      return;
    }
  }

  protected convert(data: DataModel): any[] {
    const dataList = this._data.data as any[];
    this.heatMapData = this.parseData(GTSLib.flatDeep(dataList));
    return [];
  }

  private parseData(dataList: any[]) {
    const details = [];
    const values = [];
    const dates = [];
    const data = {};
    const reducer = (accumulator, currentValue) => accumulator + parseInt(currentValue, 10);
    this.LOG.debug(['parseData'], dataList);
    dataList.forEach((gts, i) => {
      const name = GTSLib.serializeGtsMetadata(gts);
      gts.v.forEach(v => {
        const refDate = moment.utc(v[0] / 1000).startOf('day').toISOString();
        if (!data[refDate]) {
          data[refDate] = [];
        }
        if (!values[refDate]) {
          values[refDate] = [];
        }
        dates.push(v[0] / 1000);
        values[refDate].push(v[v.length - 1]);
        data[refDate].push({
          name,
          date: v[0] / 1000,
          value: v[v.length - 1],
          color: ColorLib.getColor(i, this._options.scheme),
          id: i
        });
      });
    });
    Object.keys(data).forEach((d: string) => {
      details.push({
        date: moment.utc(d),
        total: values[d].reduce(reducer),
        details: data[d],
        summary: []
      });
    });
    return details;
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div class="wrapper">
  <calendar-heatmap [data]="heatMapData" overview="global"
                    [debug]="debug"
                    [minColor]="_options.minColor"
                    [maxColor]="_options.maxColor"></calendar-heatmap>
</div>

// src/components/warp-view-drilldown/warp-view-drilldown.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Element, Listen, Prop, Watch} from "@stencil/core";
import {ChartLib} from "../../utils/chart-lib";
import {DataModel} from "../../model/dataModel";
import {Param} from "../../model/param";
import {Logger} from "../../utils/logger";
import {GTSLib} from "../../utils/gts.lib";
import moment from "moment";
import {ColorLib} from "../../utils/color-lib";

/**
 *
 */
@Component({
  tag: 'warp-view-drilldown',
  styleUrl: 'warp-view-drilldown.scss',
  shadow: true
})
export class WarpViewDrillDown {
  @Prop() responsive: boolean = false;
  @Prop() showLegend: boolean = true;
  @Prop() data: DataModel | any[] | string;
  @Prop() options: Param = new Param();
  @Prop({mutable: true}) width = '';
  @Prop({mutable: true}) height = '';

  @Element() el: HTMLElement;

  private LOG: Logger = new Logger(WarpViewDrillDown);
  private _options: Param = {
    gridLineColor: '#8e8e8e'
  };
  private resizeTimer;
  private parentWidth = -1;
  private heatMapData: any;

  @Listen('window:resize')
  onResize() {
    if (this.el.parentElement.clientWidth !== this.parentWidth) {
      this.parentWidth = this.el.parentElement.clientWidth;
      clearTimeout(this.resizeTimer);
      this.resizeTimer = setTimeout(() => {
        this.LOG.debug(['onResize'], this.el.parentElement.clientWidth);
        this.drawChart();
      }, 250);
    }
  }

  @Watch('data')
  private onData(newValue: DataModel | any[], oldValue: DataModel | any[]) {
    if (oldValue !== newValue) {
      this.LOG.debug(['data'], newValue);
      this.drawChart();
    }
  }

  @Watch('options')
  private onOptions(newValue: Param, oldValue: Param) {
    if (oldValue !== newValue) {
      this.LOG.debug(['options'], newValue);
      this.drawChart();
    }
  }

  private drawChart() {
    this._options = ChartLib.mergeDeep(this._options, this.options);
    this.height = (this.responsive ? this.el.parentElement.clientHeight : this.height || 600) + '';
    this.width = (this.responsive ? this.el.parentElement.clientWidth : this.width || 800) + '';
    if (!this.data) return;
    let data: any = this.data;
    if (typeof data === 'string') {
      data = JSON.parse(data as string);
    }
    if (GTSLib.isArray(data) && data[0] && (data[0] instanceof DataModel || data[0].hasOwnProperty('data'))) {
      data = data[0];
    }
    let dataList: any[];
    if (data instanceof DataModel || data.hasOwnProperty('data')) {
      dataList = data.data as any[];
    } else {
      dataList = data;
    }
    this.heatMapData = this.parseData(GTSLib.flatDeep(dataList));
  }


  private parseData(dataList: any[]) {
    const details = [];
    let values = [];
    const dates = [];
    const data = {};
    const reducer = (accumulator, currentValue) => accumulator + parseInt(currentValue);
    this.LOG.debug(['parseData'], dataList);
    dataList.forEach((gts, i) => {
      const name = GTSLib.serializeGtsMetadata(gts);
      gts.v.forEach(v => {
        const refDate = moment.utc(v[0] / 1000).startOf('day').toISOString();
        if (!data[refDate]) {
          data[refDate] = [];
        }
        if (!values[refDate]) {
          values[refDate] = [];
        }
        dates.push(v[0] / 1000);
        values[refDate].push(v[v.length - 1]);
        data[refDate].push({
          name: name,
          date: v[0] / 1000,
          value: v[v.length - 1],
          color: ColorLib.getColor(i),
          id: i
        });
      });
    });
    Object.keys(data).forEach((d: string) => {
      details.push({
        date: moment.utc(d),
        total: values[d].reduce(reducer),
        details: data[d],
        summary: []
      })
    });
    return details;
  }

  componentDidLoad() {
    this.drawChart()
  }

  render() {
    // noinspection CheckTagEmptyBody
    return <div class="wrapper">
      <calendar-heatmap data={this.heatMapData} overview={'global'}
                        minColor={this._options.minColor}
                        maxColor={this._options.maxColor}></calendar-heatmap>
    </div>;
  }

}
