// src/components/warp-view-modal/warp-view-modal.tsx
/*
 *  Copyright 2018  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {Component, Element, Event, EventEmitter, Method, Prop, Watch} from "@stencil/core";

@Component({
  tag: 'warp-view-modal',
  styleUrl: 'warp-view-modal.scss',
  shadow: true
})
export class WarpViewModal {

  @Prop() modalTitle: string = '';
  @Prop() kbdLastKeyPressed: string[] = [];

  @Element() el: HTMLElement;
  @Event() warpViewModalOpen: EventEmitter;
  @Event() warpViewModalClose: EventEmitter;

  private opened: boolean = false;


  @Method()
  public open() {
    this.el.style.display = 'block';
    this.el.style.zIndex = '999999';
    this.opened = true;
    this.warpViewModalOpen.emit({});
  }

  @Method()
  public close() {
    this.el.style.display = 'none';
    this.el.style.zIndex = '-1';
    this.opened = false;
    this.warpViewModalClose.emit({});
  }

  @Method()
  public isOpened(): Promise<boolean> {
    return new Promise<boolean>(resolve => {
      resolve(this.opened);
    });
  }

  @Watch('kbdLastKeyPressed')
  handleKeyDown(key: string[]) {
    if ('Escape' === key[0]) {
      this.close();
    }
  }

  componentDidLoad() {
    this.el.addEventListener('click', (event: any) => {
      if (event.path[0].nodeName === 'WARP-VIEW-MODAL') {
        this.close()
      }
    });
  }

  render() {
    return <div class="popup">
      <div class="header">
        <div class="title" innerHTML={this.modalTitle}/>
        <div class="close" onClick={() => this.close()}>&times;</div>
      </div>
      <div class="body">
        <slot/>
      </div>
    </div>
  }

}

// src/app/elements/warp-view-modal/warp-view-modal.component.ts
/*
 *  Copyright 2020  SenX S.A.S.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

import {AfterViewInit, Component, ElementRef, EventEmitter, HostListener, Input, Output, ViewEncapsulation} from '@angular/core';

@Component({
  selector: 'warpview-modal',
  templateUrl: './warp-view-modal.component.html',
  styleUrls: ['./warp-view-modal.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class WarpViewModalComponent implements AfterViewInit {


  @Input('modalTitle') modalTitle = '';
  @Input('kbdLastKeyPressed') kbdLastKeyPressed: string[] = [];

  @Output('warpViewModalOpen') warpViewModalOpen = new EventEmitter<any>();
  @Output('warpViewModalClose') warpViewModalClose = new EventEmitter<any>();

  private opened = false;

  public open() {
    this.el.nativeElement.style.display = 'block';
    this.el.nativeElement.style.zIndex = '999999';
    this.opened = true;
    this.warpViewModalOpen.emit({});
  }

  public close() {
    this.el.nativeElement.style.display = 'none';
    this.el.nativeElement.style.zIndex = '-1';
    this.opened = false;
    this.warpViewModalClose.emit({});
  }

  public isOpened(): Promise<boolean> {
    return new Promise<boolean>(resolve => {
      resolve(this.opened);
    });
  }

  @HostListener('kbdLastKeyPressed', ['$event'])
  handleKeyDown($event: string[]) {
    if ('Escape' === $event[0]) {
      this.close();
    }
  }

  constructor(private el: ElementRef) {
  }

  ngAfterViewInit(): void {
    this.el.nativeElement.addEventListener('click', (event: any) => {
      if (event.path[0].nodeName === 'WARP-VIEW-MODAL') {
        this.close();
      }
    });
  }
}

<!--
  ~  Copyright 2020  SenX S.A.S.
  ~
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
  ~
  -->

<div class="popup">
  <div class="header">
    <div class="title" [innerHTML]="modalTitle"></div>
    <div class="close" (click)="close()">&times;</div>
  </div>
  <div class="body">
    <ng-content></ng-content>
  </div>
</div>
